project:
  type: website
  execute-dir: project
  output-dir: _site
  render:
    - preprocessing.qmd
    - imputation.qmd
    - modelling.qmd
    - studyb.qmd
    - supplement.qmd
    - manuscript.qmd
  preview:
    watch-inputs: true

execute:
  freeze: auto

repo-url: https://github.com/nballou/basic-needs-in-games
site-url: https://nballou.github.io/basic-needs-in-games/
data-url: https://doi.org/10.5281/zenodo.18352505
data-license: CC0