{
  "hash": "d15a1a6729772dfe279f2355cc0d6696",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: |\n  All BANG, little buck: Basic psychological needs are weakly linked with video gaming behavior\nabstract: |\n  Psychological theories of media use often assume that subjective motivation affects observable behavior. Using video games as a test case, we examine this assumption by pairing repeated self-reports of motivation with objective digital trace data at scale. Across two datasets comprising tens of thousands of hours of gaming behavior, we test predictions derived from self-determination theory and the Basic Needs in Games (BANG) model, which posit that autonomy, competence, and relatedness experiences drive engagement. Study A (preregistered) analyzes 11k daily observations from 555 U.S. players with 30 days of multi-platform digital trace data. Study B (exploratory) examines 102k sessions from 9k PowerWash Simulator players, linking in-game experience prompts to behavioral logs. In both studies, need satisfaction was robustly associated with subjective states but showed weak or null associations with short-term gaming behavior, including subsequent play, session length, and return latency, across extensive preregistered and robustness analyses. These findings reveal a substantial motivation--behavior gap and suggest that SDT-based accounts may overestimate the role of need satisfaction in explaining when or how much people play. Data and code are available under a {{< meta data-license >}} license at {{< meta data-url >}}.\nauthor:\n  - name: Nick Ballou\n    corresponding: true\n    orcid: 0000-0003-4126-0696\n    email: nick@nickballou.com\n    affiliations: [ref: 1, ref: 2]\n  - name: Tamás Andrei Földes\n    orcid: 0000-0002-0623-9149\n    affiliations: [ref: 2]\n  - name: Matti Vuorre\n    orcid: 0000-0001-5052-066X\n    affiliations: [ref: 3]\n  - name: Thomas Hakman\n    orcid: 0009-0009-8292-2482\n    affiliations: [ref: 2]\n  - name: Kristoffer Magnusson\n    orcid: 0000-0003-0713-0556\n    affiliations: [ref: 4, ref: 2]\n  - name: Andrew K Przybylski\n    corresponding: true\n    orcid: 0000-0001-5547-2185\n    affiliations: [ref: 2]\naffiliations:\n  - id: 1\n    name: Imperial College London\n  - id: 2\n    name: University of Oxford\n  - id: 3\n    name: Tilburg University\n  - id: 4\n    name: Karolinska Institute\ncsl: https://www.zotero.org/styles/apa\nbibliography: references.bib\nkeywords: [motivation, digital trace data, video games, self-determination theory, displacement, compensatory behavior]\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n    toc-location: right\n    number-sections: true\n    code-fold: true\n    code-summary: \"Show code\"\n    code-tools: true\n    embed-resources: false\nknitr:\n  opts_chunk:\n    warning: false\n    message: false\n    fig-width: 6\n    fig-asp: 0.618\n    out-width: 80%\n    fig-align: center\ndata-license: CC0\ndata-url: https://doi.org/10.5281/zenodo.18352505\n---\n\n<!--\nNOTE: this document is the manuscript body only. It reads every computed\nobject from the targets pipeline (preprocessing / imputation / modelling /\nstudyb) via tar_load(); it fits no models itself. Model diagnostics live in\nmodelling.qmd; the appendix and sensitivity analyses live in supplement.qmd.\n-->\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-summary=\"Show code (Load required R packages)\"}\nlibrary(tidyverse)\nlibrary(glue)\nlibrary(glmmTMB)\nlibrary(mice)\nlibrary(marginaleffects)\nlibrary(broom.mixed)\nlibrary(modelsummary)\nlibrary(psych)\nlibrary(tinytable)\nlibrary(patchwork)\nlibrary(ggridges)\nlibrary(ggdist)\nlibrary(scales)\nlibrary(janitor)\nlibrary(targets)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-summary=\"Show code (Presentation constants and pipeline inputs)\"}\nset.seed(8675309)\noptions(scipen = 999)\n\ntheme_set(theme_minimal())\ntheme_update(\n  plot.background = element_rect(fill = \"white\", color = NA),\n  panel.background = element_rect(fill = \"white\", color = NA),\n  strip.background = element_rect(fill = \"black\"),\n  strip.text = element_text(color = \"white\", size = 10),\n  axis.text = element_text(color = \"black\", size = 10),\n  panel.grid.minor = element_blank(),\n  panel.border = element_rect(colour = \"black\", fill = NA, linewidth = 1)\n)\n\nsource(\"R/helpers.R\") # colors, labels, and reporting helpers\nsource(\"R/targets/imputation.R\") # build_wide_survey(), setup_mice_inputs()\n\ntar_load(c(\n  surveys, intake, hourly_telemetry, daily_telemetry, activity_categories,\n  dat, dat_desc, m_imputations,\n  h1_pooled, h1mod, h2_pooled, h2mod, h3_pooled, h3mod,\n  pws_m1, pws_m2, pws_wide, pws_n_players, pws_n_sessions\n))\n\nfull_eligible_pids <- unique(surveys$pid)\npws_n_players_fmt <- scales::comma(pws_n_players)\npws_n_sessions_fmt <- scales::comma(pws_n_sessions)\n```\n:::\n\n\n# Introduction\n\nDigital technology use constitutes one of the domains in which behavior is most directly observable. Digital media (1) are widely used---upwards of half of adults and nearly all children in the UK and US regularly play video games [@EntertainmentSoftwareAssociation20242024; @Ofcom2023Online]; (2) generate digital trace data (automatically logged histories of user behavior), and (3) affect the health of at least some users in important ways, both for better and for worse [@GranicEtAl2014benefits; @BallouEtAl2024How]. These putative impacts of media use behavior on health are of interest to users, industry professionals, policymakers, clinicians, and families, but research to date has had limited success supporting these groups [@Ballou2023Manifesto]. Among other difficulties, progress has been stymied by three challenges: (1) accessing granular behavioral data, (2) measuring mental health with sufficient temporal detail, and (3) aligning theory with growing evidence that effects relate primarily to the quality, rather than quantity, of play [@BallouDeterding2024Basic; @Buchi2024Digital; @Orben2022Digital].\n\nDigital trace data—histories of user actions generated when interacting with games—addresses several of these challenges. Compared to self-report, trace data provides greater detail about what, when and how much people play while alleviating concerns about recall biases [@ErnalaEtAl2020How; @KahnEtAl2014why; @ParryEtAl2021systematic]. However, three key limitations remain. First, while gaming companies collect player data at scale [@El-NasrEtAl2021Game], these data are rarely accessible to independent researchers. Where access has been negotiated or engineered via open source methods, it typically covers just one game or platform. While single-game studies can offer high depth and detail, they are potentially a small part of a person's gaming diet---engaged UK and US players use an average of 2.8 platforms [@BallouEtAl2025Perceived]. Given this, we advocate for openly available digital trace data spanning both single-game studies and multi-platform data access to understand holistic effects.\n\nSecond, while trace data is often richly longitudinal, it has to date only been paired with wellbeing surveys consisting of either a single measurement wave [@BallouEtAl2025Perceived; @JohannesEtAl2021Video] or waves separated by multiple weeks [@LarrieuEtAl2023How; @VuorreEtAl2022Time]. Early evidence suggests gaming effects may materialize and dissipate within 6 hours [@VuorreEtAl2023Affective; @BallouEtAl2025Perceived], and subjective wellbeing varies substantially across a day [@LuhmannEtAl2021Subjective]. Experience sampling and daily diary methods, embraced in social media research [@AalbersEtAl2021Caught; @SiebersEtAl2021Explaining], are needed to capture nuanced, short-lived effects and to better differentiate within- and between-person relationships [@JohannesEtAl2024How].\n\nThird, effects of gaming are likely nuanced and contextual, but existing research lacks strong theoretical frameworks to guide investigation. Studies using digital trace data have ruled out simple playtime--wellbeing relationships [@BallouEtAl2024Registered; @JohannesEtAl2021Video; @VuorreEtAl2022Time; @LarrieuEtAl2023How; @BallouEtAl2025Perceived], supporting calls to move beyond quantity-focused approaches [@BallouEtAl2025How]. To do so, we need theory-driven predictions about how psychological states relate to gaming behavior itself—what motivates people to play in the first place, and how daily fluctuations in wellbeing shape engagement patterns. Self-Determination Theory [SDT, @Ryan2023Oxforda] offers such a framework, proposing that satisfaction of basic psychological needs---autonomy, competence, and relatedness---drives motivated behavior including media use. Understanding whether and when people choose to play games may depend critically on their experiences of needs satisfaction in daily life, yet the majority of studies that have tested these behavioral predictions did so without access to intensive longitudinal data [e.g., @BenderGentile2019internet; @AllenAnderson2018satisfaction].\n\nTogether, these gaps point to clear next steps: collect digital trace data in the form of both comprehensive multi-platform records and single-game, granular interactions; pair it with high-resolution, repeated wellbeing measurements; and use this data for theory-driven investigations of play quality and context. These are the aims of the present study.\n\n# Self-determination theory\n\nSelf-determination theory [@RyanDeci2017Selfdetermination] proposes three innate and universal psychological needs: the need for autonomy (to feel in control over one’s life and volitional in one’s actions), competence (to act effectively and exert mastery in the world), and relatedness (to feel that one is valued by others and values them in return). These basic psychological needs are theorized to be direct antecedents of intrinsic and autonomous motivation, as well as vital nutriments required for a person to live a fully functional life [@Ryan2023Oxford]. Across the environments we inhabit and activities we perform, these needs can be either satisfied or frustrated [@VansteenkisteEtAl2020basic]. \n\nThere has been substantial research into how games and other entertainment media can support basic psychological needs [@PrzybylskiEtAl2010motivational; @TyackMekler2020Selfdetermination]. Games are adept at satisfying all three basic needs; games that better satisfy needs are more engaging; and having one’s needs satisfied during gaming is associated with better mental health outcomes during and after play [@ReerQuandt2020Digital; @TyackMekler2020Selfdetermination; @VellaJohnson2012Flourishing]. A large body of work supports that basic need satisfaction supports intrinsic motivation, and intrinsic motivation translates to higher self-reported behavioral engagement [@RyanEtAl2022We]. \n\n## The Basic Needs in Games (BANG) Model\n\nThe Basic Needs in Games (BANG) model of video game play and mental health [@BallouDeterding2024Basic] builds upon the core SDT principle that any action’s impact on mental health is mediated by the extent to which it satisfies or frustrates basic psychological needs. By differentiating between playtime and quality of play, BANG seeks to explain seemingly conflicting earlier findings that playtime itself is largely unrelated to wellbeing, but that some players do experience meaningful benefits or harms from their video game play. \n\nTo date, however, BANG remains largely untested. Hence, the goal of this study is to test several key BANG hypotheses. We label the hypotheses of the current study in numerical order (e.g., H1) but also provide the numbered label from the original paper (e.g., B6) for clarity of potential falsification.\n\n### The Relationship Between Basic Needs in Games and Global Basic Needs (H1)\n\nFollowing the hierarchical model of intrinsic and extrinsic motivation [@Vallerand1997Hierarchical], BANG conceives of basic needs as operating at three levels of generality: situational (a particular gaming session), contextual (gaming as a whole), and global (one’s life in general). Experiences at lower levels of generality feed into and co-constitute higher levels---experiences with games are one (greater or lesser) element of one's life overall. \n\nA positive relationship between need satisfaction in games and overall need satisfaction is well-established in prior literature [@AllenAnderson2018satisfaction; @BallouEtAl2024Basic; @BradtEtAl2024Are]. BANG (B6) formalizes this relationship, proposing that need satisfaction experienced during gaming sessions contributes to overall need satisfaction in life. Thus, BANG hypothesizes:\n\n*H1. When individuals’ in-game needs are better satisfied, they report greater overall need satisfaction.*\n\n### Expectations (H2a)\n\nEarly articulations of SDT propose that goal or activity selection is (intrinsically) motivated by the 'awareness of potential satisfaction' of basic psychological needs or 'expectations about the satisfaction of those [salient] motives' [@DeciRyan1985Intrinsic, p. 231--239]. Need-related outcome expectations are closely related to intrinsic motivation [perhaps even forming part of the computational machinery underlying motivation @MurayamaJach2023critique], and the behavioral product of these expectations is therefore greater behavioral engagement. \n\nExpectations have, perhaps surprisingly, not featured prominently in subsequent empirical work; most gaming and media use-related SDT work focuses on need satisfaction or frustration as the experiential consequence of media consumption [@BallouDeterding2023Basic]. Need experiences can explain loops of self-sustaining activity, but cannot explain initial selective exposure to gaming where the activity has not commenced. \n\nBANG proposes that experiences of need satisfaction during a particular gaming session positively affect players' expectations for future need satisfaction with the current game, similar games, and gaming as a whole. This prediction is grounded in reports that expected need frustration is reported to modulate both initial and continued gaming exposure [@BallouDeterding2023Just], and in broader findings that outcome expectations are a strong predictor of continued media engagement [@ChangEtAl2014effects; @KocakAlanEtAl2022Replaying; @LaroseEtAl2001Understanding]. From BANG (B8), we therefore derive the following hypothesis:\n\n*H2a. When individuals’ in-game need satisfaction is higher, they are more likely to play video games in the 24-hour period after survey completion.*\n\n### Compensation (H2b)\n\nSDT predicts that (global) need frustration results in compensatory behavior---people attempt to replenish needs that are not being met by altering their behavior [e.g., @SheldonEtAl2011twoprocess]. The potent need satisfaction offered by games constitute one way for people to compensate, particularly those who are highly engaged with gaming and have high gaming literacy [@BallouEtAl2022People]. The so-called \"need density hypothesis\" predicts that problematic or disordered gaming is most likely to occur when a person experiences high need satisfaction in games and high need frustration in other life domains [@RigbyRyan2011glued]. In other words, problematic gaming is theorized to occur, at least for some, due to a negative feedback loop whereby compensation occurs and becomes maladaptive such that the person's other compensatory tools besides gaming are progressively diminished. Several studies have found support for the need density hypothesis account [@BradtEtAl2024Are; @AllenAnderson2018satisfaction; @MillsEtAl2018exploring]. \n\nBANG operationalizes this compensatory play via intrinsic motivation. Frustrated needs in one’s life in general make opportunities to fulfill those needs more salient, which---all else equal---manifests phenomenologically as a stronger preference towards activities that satisfy the frustrated need(s). Given this, we hypothesize in the context of our sample of moderately to highly-engaged video game players (derived from BANG Hypothesis 9):\n\n*H2b. When individuals’ global need frustration is higher, they are more likely to play video games in the 24-hour period after survey completion.* \n\n### Displacement (H3)\n\nPlaytime, BANG argues, only becomes problematic when it displaces other activities essential to the maintenance of need satisfaction in life overall. Commonly proposed problematic displacements are work/school responsibilities [@DrummondSauer2020Timesplitters], personal relationships [@DomahidiEtAl2018Longitudinal], and physical health or sleep [@KingEtAl2013impact]. Displacing these essential activities would thereby reduce global need satisfaction. Thus, BANG (B5) hypothesizes:\n\n*H3. When a person’s most recent gaming is reported to displace a core life domain (work/school, social engagements, sleep/eating/fitness, or caretaking), their global need satisfaction is lower.*\n\n# Study A: Preregistered Analysis of Multi-Platform Digital Trace Data and Daily Surveys\n\nStudy A was pre-registered on the Open Science Framework (OSF) in the form of a Stage 1 Programmatic Registered Report [@BallouEtAl2025Psychological] at *Peer Community In: Registered Reports*. The present Study A corresponds to Study 1 in the programmatic Registered Report; two other preregistered Stage 2 outputs, focused on sleep (Registered Report Study 2) and genres (Registered Report Study 3), respectively, are forthcoming. \n\nAll data and analysis code are available on Zenodo ({{< meta data-url >}}).\n\n## Study A Method\n\n::: {.place arguments='top, scope: \"parent\", float: true'}\n\n\n::: {#tbl-platforms .cell layout-align=\"center\" tbl-cap='Platform Details'}\n\n```{.r .cell-code  code-summary=\"Show code (Create platform details table)\"}\ntibble(\n  Platform = c(\n    \"Nintendo\",\n    \"Xbox\",\n    \"Steam\"\n  ),\n  `Data Source` = c(\n    \"Data-sharing agreements with Nintendo of America\",\n    \"Data-sharing agreement with Microsoft\",\n    \"Custom web app (Gameplay.Science)\"\n  ),\n  `Account Linking Process` = c(\n    \"Participants shared an identifier contained within a QR code on the Nintendo web interface. Nintendo of America uses this identifier to retrieve gameplay data and share it with the research team.\",\n    \"Participants consented to data sharing by opting in to the study on Xbox Insiders with their Xbox account. Microsoft retrieved and shared pseudonymized gameplay data for all consented accounts.\",\n    \"Using a web app we developed (https://gameplay.science), participants consented to have their gameplay data monitored for the duration of the study. Authentication uses the official Steam API (OpenID).\"\n  ),\n  `Type of Data Collected` = c(\n    \"Session records (what game was played, at what time, for how long) for first-party games only (games published in whole or in part by Nintendo).\",\n    \"Session records (what game was played, at what time, for how long). Game titles were replaced with a random persistent identifier, but genre(s) and age ratings are shared.\",\n    \"Hourly aggregates per game (every hour, the total time spent playing each game during the previous hour)\"\n  )\n) |>\n  tt(\n    escape = TRUE,\n    notes = list(\n      \"a\" = list(\n        i = 1,\n        j = 3,\n        text = \"See https://accounts.nintendo.com/qrcode.\"\n      ),\n      \"b\" = list(\n        i = 1,\n        j = 4,\n        text = \"Nintendo-published games accounted for 63% of Switch playtime in our sample.\"\n      ),\n      \"c\" = list(\n        i = 2,\n        j = 3,\n        text = \"See https://support.xbox.com/en-US/help/account-profile/manage-account/guide-to-insider-program.\"\n      )\n    )\n  ) |>\n  style_tt(fontsize = 0.7) |>\n  style_tt(i = 0, bold = TRUE, align = \"c\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_y48iejn7fbh516q5a8df = TinyTable.createTableFunctions(\"tinytable_y48iejn7fbh516q5a8df\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '3', j: 1 }, { i: '3', j: 2 }, { i: '3', j: 3 }, { i: '3', j: 4 } ], css_id: 'tinytable_css_mpvalump5f7tkeoe3dga',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 } ], css_id: 'tinytable_css_nrfvnkby08gpukg40cin',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 } ], css_id: 'tinytable_css_3i5y0xq3sn67ydotb8ty',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_y48iejn7fbh516q5a8df.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_y48iejn7fbh516q5a8df td.tinytable_css_mpvalump5f7tkeoe3dga, #tinytable_y48iejn7fbh516q5a8df th.tinytable_css_mpvalump5f7tkeoe3dga {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-size: 0.7em }\n    #tinytable_y48iejn7fbh516q5a8df td.tinytable_css_nrfvnkby08gpukg40cin, #tinytable_y48iejn7fbh516q5a8df th.tinytable_css_nrfvnkby08gpukg40cin { font-size: 0.7em }\n    #tinytable_y48iejn7fbh516q5a8df td.tinytable_css_3i5y0xq3sn67ydotb8ty, #tinytable_y48iejn7fbh516q5a8df th.tinytable_css_3i5y0xq3sn67ydotb8ty {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-weight: bold; text-align: center; font-size: 0.7em }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_y48iejn7fbh516q5a8df\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Platform</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Data Source</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Account Linking Process</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Type of Data Collected</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='4'><sup>a</sup> See https://accounts.nintendo.com/qrcode.</td></tr>\n<tr><td colspan='4'><sup>b</sup> Nintendo-published games accounted for 63% of Switch playtime in our sample.</td></tr>\n<tr><td colspan='4'><sup>c</sup> See https://support.xbox.com/en-US/help/account-profile/manage-account/guide-to-insider-program.</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Nintendo</td>\n                  <td data-row=\"1\" data-col=\"2\">Data-sharing agreements with Nintendo of America</td>\n                  <td data-row=\"1\" data-col=\"3\">Participants shared an identifier contained within a QR code on the Nintendo web interface. Nintendo of America uses this identifier to retrieve gameplay data and share it with the research team.<sup>a</sup></td>\n                  <td data-row=\"1\" data-col=\"4\">Session records (what game was played, at what time, for how long) for first-party games only (games published in whole or in part by Nintendo).<sup>b</sup></td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Xbox</td>\n                  <td data-row=\"2\" data-col=\"2\">Data-sharing agreement with Microsoft</td>\n                  <td data-row=\"2\" data-col=\"3\">Participants consented to data sharing by opting in to the study on Xbox Insiders with their Xbox account. Microsoft retrieved and shared pseudonymized gameplay data for all consented accounts.<sup>c</sup></td>\n                  <td data-row=\"2\" data-col=\"4\">Session records (what game was played, at what time, for how long). Game titles were replaced with a random persistent identifier, but genre(s) and age ratings are shared.</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Steam</td>\n                  <td data-row=\"3\" data-col=\"2\">Custom web app (Gameplay.Science)</td>\n                  <td data-row=\"3\" data-col=\"3\">Using a web app we developed (https://gameplay.science), participants consented to have their gameplay data monitored for the duration of the study. Authentication uses the official Steam API (OpenID).</td>\n                  <td data-row=\"3\" data-col=\"4\">Hourly aggregates per game (every hour, the total time spent playing each game during the previous hour)</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n:::\n\n### Design\n\nThe data for this study comprise a subset of the data from the Open Play study [@BallouEtAl2025Open], version 1.2.5. In the Open Play study, participants provided access to automated records of their gaming history on one or more platforms (Xbox, Steam, Nintendo Switch, iOS, Android) and completed an intake survey followed by a 30-day daily diary study. The intake survey included demographic questions and baseline measures of wellbeing. Daily data was collected between Oct 2024 and Aug 2025. \n\nParticipants were recruited in collaboration with two panel providers, Prolific and PureProfile. Participants were eligible if they were aged 18 or older, resided in the United States, self-reported playing video games for at least 1 hour per week with ≥50% of that gaming taking place on eligible platforms (Nintendo, Xbox, and Steam), and successfully linked at least one gaming account on Xbox, Steam, and/or Nintendo Switch with validated recent digital trace data. iOS and Android data were collected but are not used in this analysis. For full details of the recruitment procedures and study methodology, see [@BallouEtAl2025Open].\n\n### Ethics\n\nThis study received ethical approval from the Social Sciences and Humanities Inter-Divisional Research Ethics Committee at the University of Oxford (OII_CIA_23_107). All participants provided informed consent at the start of the study, including consent to their data being shared openly for reanalysis.\n\nParticipants were paid at an average rate of £12/hour, equating to: £0.20 for a 1-minute screening, £2 for the 10-minute intake survey (plus £5 for linking at least one account with recent data), £0.80 for each 4-minute daily survey. Participants received a £10 bonus payment for completing at least 24 out of 30 daily surveys.\n\n### Sample Size Justification \n\nAs specified in the Stage 1 Registered Report, sample size was determined by feasibility/resources rather than a formal power analysis, with an initial target of recruiting up to 1,000 U.S. participants into the diary component, with ~30% expected attrition. Sensitivity analyses showed that this sample size was sufficient to estimate target associations with moderate precision (95% CI spanning .13 scale points on a 7-point scale) (https://github.com/digital-wellbeing/platform-study-rr).\n\n### Participant Inclusion/Exclusion Criteria\n\nAll eligibility and exclusion criteria were specified prior to data analysis in Stage 1 and/or documented as deviations in @tbl-deviations. Participants were eligible if they were aged 18+, resided in the U.S., reported playing video games at least 1 hour/week, reported that a substantial share of their gaming occurred on eligible platforms (Nintendo/Xbox/Steam), and successfully linked at least one eligible account with validated recent digital trace data. As documented, two eligibility thresholds were adjusted for feasibility relative to Stage 1: the platform-share requirement was lowered (75% → 50%), and the recent valid trace requirement was extended (7 days → 14 days).\n\nParticipants who completed fewer than 15 daily surveys were excluded from the primary (imputed) analyses. The ≥15-survey threshold aligns with the Stage 1 criterion of avoiding analyses that would require imputing more data than collected (≥50%).\n\n### Participants\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-summary=\"Show code (Calculate participant statistics and response rates)\"}\n# Analytic sample (≥15 completions, used in imputed analyses)\nanalytic_pids <- dat |>\n  filter(.imp == 1) |>\n  distinct(pid) |>\n  pull(pid)\n\n# Prepare participant data with collapsed categories\nparticipant_data <- intake |>\n  filter(pid %in% c(full_eligible_pids, analytic_pids)) |>\n  mutate(\n    # Collapse gender to main categories\n    gender = ifelse(\n      gender %in% c(\"Man\", \"Woman\"),\n      gender,\n      \"Other gender identity\"\n    ),\n    # Collapse ethnicity to main categories\n    ethnicity_collapsed = case_when(\n      str_detect(ethnicity, \"White\") ~ \"White\",\n      str_detect(\n        ethnicity,\n        \"Black|African American|African, Caribbean\"\n      ) ~ \"Black/African American\",\n      str_detect(ethnicity, \"Asian\") ~ \"Asian\",\n      str_detect(ethnicity, \"Two or More|Mixed\") ~ \"Multiracial\",\n      is.na(ethnicity) ~ NA_character_,\n      TRUE ~ \"Other\"\n    ),\n    # Collapse education to main levels\n    education_collapsed = case_when(\n      str_detect(\n        edu_level,\n        \"Less than|No formal|Primary\"\n      ) ~ \"Less than high school\",\n      str_detect(\n        edu_level,\n        \"High school|Secondary School|GCSE|Some college|Some University\"\n      ) ~ \"High school or some college\",\n      str_detect(edu_level, \"Associate\") ~ \"Associate degree\",\n      str_detect(\n        edu_level,\n        \"Bachelor|University Bachelors\"\n      ) ~ \"Bachelor's degree\",\n      str_detect(\n        edu_level,\n        \"Master|Graduate|professional degree|doctoral|post-graduate\"\n      ) ~ \"Graduate degree\",\n      is.na(edu_level) ~ NA_character_,\n      TRUE ~ \"Other\"\n    ),\n    # Assign to sample\n    sample = case_when(\n      pid %in% analytic_pids ~ \"Analytic sample\",\n      TRUE ~ \"Full eligible sample\"\n    )\n  ) |>\n  select(\n    pid,\n    sample,\n    age,\n    gender,\n    ethnicity_collapsed,\n    education_collapsed,\n    self_reported_weekly_play,\n    diaries_completed\n  )\n\n# Sample sizes for text\nn_analytic <- sum(participant_data$sample == \"Analytic sample\")\nn_full <- sum(\n  participant_data$sample %in% c(\"Analytic sample\", \"Full eligible sample\")\n)\n\n# Gender summary for analytic sample (for text)\ngender_analytic <- participant_data |>\n  filter(sample == \"Analytic sample\") |>\n  count(gender) |>\n  mutate(pct = 100 * n / sum(n))\n\npct_men <- gender_analytic |> filter(gender == \"Man\") |> pull(pct) |> round(1)\npct_women <- gender_analytic |>\n  filter(gender == \"Woman\") |>\n  pull(pct) |>\n  round(1)\npct_other <- gender_analytic |>\n  filter(gender == \"Other gender identity\") |>\n  pull(pct) |>\n  round(1)\n\ngender_summary <- glue(\n  \"{pct_men}% men, {pct_women}% women, {pct_other}% other gender identities\"\n)\n```\n:::\n\n\n\n::: {#tbl-participants .cell layout-align=\"center\" tbl-cap='Participant characteristics by sample'}\n\n```{.r .cell-code  code-summary=\"Show code (Generate participant demographics table)\"}\n# Build table using map\nsummary_table <- bind_rows(\n  # Sample sizes\n  tibble(\n    Characteristic = \"**N**\",\n    `Full sample` = as.character(n_full),\n    `Analytic sample` = as.character(n_analytic)\n  ),\n\n  # Age\n  tibble(\n    Characteristic = \"Age (years)\",\n    `Full sample` = format_mean_sd(\n      participant_data$age[participant_data$sample == \"Full eligible sample\"]\n    ),\n    `Analytic sample` = format_mean_sd(\n      participant_data$age[participant_data$sample == \"Analytic sample\"]\n    )\n  ),\n\n  # Categorical demographics\n  create_categorical_section(\n    participant_data,\n    \"gender\",\n    \"Gender\",\n    c(\"Man\", \"Woman\", \"Other gender identity\")\n  ),\n\n  create_categorical_section(\n    participant_data,\n    \"ethnicity_collapsed\",\n    \"Ethnicity\",\n    c(\"White\", \"Black/African American\", \"Asian\", \"Multiracial\", \"Other\")\n  ),\n\n  create_categorical_section(\n    participant_data,\n    \"education_collapsed\",\n    \"Education\",\n    c(\n      \"Less than high school\",\n      \"High school or some college\",\n      \"Associate degree\",\n      \"Bachelor's degree\",\n      \"Graduate degree\"\n    )\n  ),\n\n  # Gaming behavior section\n  tibble(\n    Characteristic = \"**Gaming behavior**\",\n    `Full sample` = \"\",\n    `Analytic sample` = \"\"\n  ),\n\n  tibble(\n    Characteristic = \"Weekly play (hours)\",\n    `Full sample` = format_mean_sd(\n      participant_data$self_reported_weekly_play[\n        participant_data$sample == \"Full eligible sample\"\n      ] /\n        60\n    ),\n    `Analytic sample` = format_mean_sd(\n      participant_data$self_reported_weekly_play[\n        participant_data$sample == \"Analytic sample\"\n      ] /\n        60\n    )\n  ),\n\n  # Study engagement section\n  tibble(\n    Characteristic = \"**Study engagement**\",\n    `Full sample` = \"\",\n    `Analytic sample` = \"\"\n  ),\n\n  tibble(\n    Characteristic = \"Surveys completed\",\n    `Full sample` = format_mean_sd(\n      participant_data$diaries_completed[\n        participant_data$sample == \"Full eligible sample\"\n      ]\n    ),\n    `Analytic sample` = format_mean_sd(\n      participant_data$diaries_completed[\n        participant_data$sample == \"Analytic sample\"\n      ]\n    )\n  )\n)\n\n# Identify rows for styling\nheader_rows <- which(\n  str_detect(summary_table$Characteristic, \"^\\\\*\\\\*\") |\n    (summary_table$`Full sample` == \"\" & summary_table$`Analytic sample` == \"\")\n)\nindent_rows <- which(str_detect(summary_table$Characteristic, \"^    \"))\n\n# Create table\nsummary_table |>\n  tt(\n    notes = \"Values are M (SD) or N (%). Ethnicity and education categories collapsed to main levels for clarity.\"\n  ) |>\n  format_tt(j = 1, markdown = TRUE) |>\n  style_tt(i = header_rows, bold = TRUE) |>\n  format_tt(i = header_rows, j = 1, fn = function(x) {\n    str_remove_all(x, \"\\\\*\\\\*\")\n  }) |>\n  style_tt(i = indent_rows, j = 1, indent = 1) |>\n  format_tt(i = indent_rows, j = 1, fn = function(x) str_trim(x)) |>\n  style_tt(fontsize = 0.7) |>\n  style_tt(i = 0, bold = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_0n1y6xet8dj9e7qlfo1k = TinyTable.createTableFunctions(\"tinytable_0n1y6xet8dj9e7qlfo1k\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '22', j: 1 }, { i: '22', j: 2 }, { i: '22', j: 3 } ], css_id: 'tinytable_css_5lw8yyar941p9kmapee9',}, \n          { positions: [ { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '16', j: 1 }, { i: '17', j: 1 }, { i: '18', j: 1 } ], css_id: 'tinytable_css_k437v4evgtmce99piq0m',}, \n          { positions: [ { i: '2', j: 1 }, { i: '20', j: 1 }, { i: '2', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '16', j: 2 }, { i: '17', j: 2 }, { i: '18', j: 2 }, { i: '20', j: 2 }, { i: '2', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '14', j: 3 }, { i: '15', j: 3 }, { i: '16', j: 3 }, { i: '17', j: 3 }, { i: '18', j: 3 }, { i: '20', j: 3 } ], css_id: 'tinytable_css_75hhagi0jp3wi5ag57py',}, \n          { positions: [ { i: '1', j: 1 }, { i: '3', j: 1 }, { i: '7', j: 1 }, { i: '13', j: 1 }, { i: '19', j: 1 }, { i: '21', j: 1 }, { i: '1', j: 2 }, { i: '3', j: 2 }, { i: '7', j: 2 }, { i: '13', j: 2 }, { i: '19', j: 2 }, { i: '21', j: 2 }, { i: '1', j: 3 }, { i: '3', j: 3 }, { i: '7', j: 3 }, { i: '13', j: 3 }, { i: '19', j: 3 }, { i: '21', j: 3 } ], css_id: 'tinytable_css_kyyip2ggcxnxw8td0zxe',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_l8gc4npombc63xxd83tq',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_0n1y6xet8dj9e7qlfo1k.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_0n1y6xet8dj9e7qlfo1k td.tinytable_css_5lw8yyar941p9kmapee9, #tinytable_0n1y6xet8dj9e7qlfo1k th.tinytable_css_5lw8yyar941p9kmapee9 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-size: 0.7em }\n    #tinytable_0n1y6xet8dj9e7qlfo1k td.tinytable_css_k437v4evgtmce99piq0m, #tinytable_0n1y6xet8dj9e7qlfo1k th.tinytable_css_k437v4evgtmce99piq0m { font-size: 0.7em; padding-left: 1em }\n    #tinytable_0n1y6xet8dj9e7qlfo1k td.tinytable_css_75hhagi0jp3wi5ag57py, #tinytable_0n1y6xet8dj9e7qlfo1k th.tinytable_css_75hhagi0jp3wi5ag57py { font-size: 0.7em }\n    #tinytable_0n1y6xet8dj9e7qlfo1k td.tinytable_css_kyyip2ggcxnxw8td0zxe, #tinytable_0n1y6xet8dj9e7qlfo1k th.tinytable_css_kyyip2ggcxnxw8td0zxe { font-weight: bold; font-size: 0.7em }\n    #tinytable_0n1y6xet8dj9e7qlfo1k td.tinytable_css_l8gc4npombc63xxd83tq, #tinytable_0n1y6xet8dj9e7qlfo1k th.tinytable_css_l8gc4npombc63xxd83tq {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-weight: bold; font-size: 0.7em }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_0n1y6xet8dj9e7qlfo1k\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Characteristic</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Full sample</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Analytic sample</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='3'>Values are M (SD) or N (%). Ethnicity and education categories collapsed to main levels for clarity.</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">N</td>\n                  <td data-row=\"1\" data-col=\"2\">1217</td>\n                  <td data-row=\"1\" data-col=\"3\">555</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Age (years)</td>\n                  <td data-row=\"2\" data-col=\"2\">25.4 (4.2)</td>\n                  <td data-row=\"2\" data-col=\"3\">28.0 (5.2)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Gender</td>\n                  <td data-row=\"3\" data-col=\"2\"></td>\n                  <td data-row=\"3\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">Man</td>\n                  <td data-row=\"4\" data-col=\"2\">398 (60.1%)</td>\n                  <td data-row=\"4\" data-col=\"3\">353 (63.6%)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Woman</td>\n                  <td data-row=\"5\" data-col=\"2\">228 (34.4%)</td>\n                  <td data-row=\"5\" data-col=\"3\">159 (28.6%)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">Other gender identity</td>\n                  <td data-row=\"6\" data-col=\"2\">36 (5.4%)</td>\n                  <td data-row=\"6\" data-col=\"3\">43 (7.7%)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Ethnicity</td>\n                  <td data-row=\"7\" data-col=\"2\"></td>\n                  <td data-row=\"7\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">White</td>\n                  <td data-row=\"8\" data-col=\"2\">378 (61.1%)</td>\n                  <td data-row=\"8\" data-col=\"3\">354 (63.8%)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">Black/African American</td>\n                  <td data-row=\"9\" data-col=\"2\">74 (12.0%)</td>\n                  <td data-row=\"9\" data-col=\"3\">49 (8.8%)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">Asian</td>\n                  <td data-row=\"10\" data-col=\"2\">43 (6.9%)</td>\n                  <td data-row=\"10\" data-col=\"3\">56 (10.1%)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Multiracial</td>\n                  <td data-row=\"11\" data-col=\"2\">93 (15.0%)</td>\n                  <td data-row=\"11\" data-col=\"3\">71 (12.8%)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">Other</td>\n                  <td data-row=\"12\" data-col=\"2\">31 (5.0%)</td>\n                  <td data-row=\"12\" data-col=\"3\">25 (4.5%)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">Education</td>\n                  <td data-row=\"13\" data-col=\"2\"></td>\n                  <td data-row=\"13\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\">Less than high school</td>\n                  <td data-row=\"14\" data-col=\"2\">16 (2.4%)</td>\n                  <td data-row=\"14\" data-col=\"3\">10 (1.8%)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">High school or some college</td>\n                  <td data-row=\"15\" data-col=\"2\">366 (55.3%)</td>\n                  <td data-row=\"15\" data-col=\"3\">242 (43.6%)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\">Associate degree</td>\n                  <td data-row=\"16\" data-col=\"2\">72 (10.9%)</td>\n                  <td data-row=\"16\" data-col=\"3\">57 (10.3%)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"17\" data-col=\"1\">Bachelor's degree</td>\n                  <td data-row=\"17\" data-col=\"2\">161 (24.3%)</td>\n                  <td data-row=\"17\" data-col=\"3\">206 (37.1%)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"18\" data-col=\"1\">Graduate degree</td>\n                  <td data-row=\"18\" data-col=\"2\">37 (5.6%)</td>\n                  <td data-row=\"18\" data-col=\"3\">39 (7.0%)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"19\" data-col=\"1\">Gaming behavior</td>\n                  <td data-row=\"19\" data-col=\"2\"></td>\n                  <td data-row=\"19\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"20\" data-col=\"1\">Weekly play (hours)</td>\n                  <td data-row=\"20\" data-col=\"2\">19.2 (12.5)</td>\n                  <td data-row=\"20\" data-col=\"3\">17.7 (11.4)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"21\" data-col=\"1\">Study engagement</td>\n                  <td data-row=\"21\" data-col=\"2\"></td>\n                  <td data-row=\"21\" data-col=\"3\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"22\" data-col=\"1\">Surveys completed</td>\n                  <td data-row=\"22\" data-col=\"2\">2.8 (3.6)</td>\n                  <td data-row=\"22\" data-col=\"3\">26.3 (3.9)</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nThe current sample included 555 participants (63.6% men, 28.6% women, 7.7% other gender identities) who completed at least 15 daily surveys and were included in the main imputed analyses. The full eligible sample comprised 1217 participants who completed at least 1 survey and were included in complete case sensitivity analyses.\n\n::: {.place arguments='top, scope: \"parent\", float: true'}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-summary=\"Show code (Create main descriptive figure)\"}\n# Panel A: Density ridges for key variables\ndat_desc <- dat |> filter(.imp == 1)\n\npanel_a <- dat_desc |>\n  select(global_ns, global_nf, game_ns) |>\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"value\") |>\n  mutate(\n    variable = factor(\n      variable,\n      levels = c(\"game_ns\", \"global_ns\", \"global_nf\"),\n      labels = c(\n        sub(\" \", \"\\n\", labels[\"game_ns\"]),\n        sub(\" \", \"\\n\", labels[\"global_ns\"]),\n        sub(\" \", \"\\n\", labels[\"global_nf\"])\n      )\n    )\n  ) |>\n  ggplot(aes(x = value, y = variable, fill = variable)) +\n  geom_density_ridges(alpha = 0.7, scale = 0.9, na.rm = TRUE) +\n  scale_fill_manual(\n    values = setNames(\n      c(colors$game_ns, colors$global_ns, colors$global_nf),\n      c(\n        sub(\" \", \"\\n\", labels[\"game_ns\"]),\n        sub(\" \", \"\\n\", labels[\"global_ns\"]),\n        sub(\" \", \"\\n\", labels[\"global_nf\"])\n      )\n    )\n  ) +\n  labs(x = \"Scale Value\", y = NULL) +\n  coord_cartesian(xlim = c(1, 7)) +\n  theme(legend.position = \"none\")\n\n# Panel B: Variance decomposition\npanel_b <- dat_desc |>\n  select(pid, global_ns, global_nf, game_ns) |>\n  pivot_longer(\n    c(global_ns, global_nf, game_ns),\n    names_to = \"variable\",\n    values_to = \"value\"\n  ) |>\n  group_by(variable) |>\n  summarise(\n    var_total = var(value, na.rm = TRUE),\n    var_between = var(tapply(value, pid, mean, na.rm = TRUE), na.rm = TRUE),\n    .groups = \"drop\"\n  ) |>\n  mutate(\n    pct_between = 100 * var_between / var_total,\n    pct_within = 100 * (var_total - var_between) / var_total,\n    variable = factor(\n      variable,\n      levels = c(\"game_ns\", \"global_ns\", \"global_nf\"),\n      labels = c(\n        gsub(\" \", \"\\n\", labels[\"game_ns\"]),\n        gsub(\" \", \"\\n\", labels[\"global_ns\"]),\n        gsub(\" \", \"\\n\", labels[\"global_nf\"])\n      )\n    )\n  ) |>\n  pivot_longer(\n    c(pct_within, pct_between),\n    names_to = \"component\",\n    values_to = \"percentage\"\n  ) |>\n  mutate(\n    component = factor(\n      component,\n      levels = c(\"pct_between\", \"pct_within\"),\n      labels = c(labels[\"Between-person\"], labels[\"Within-person\"])\n    )\n  ) |>\n  ggplot(aes(x = variable, y = percentage, fill = component)) +\n  geom_col(position = \"stack\") +\n  scale_fill_manual(\n    values = c(\n      \"Between-person\" = colors$between,\n      \"Within-person\" = colors$within\n    )\n  ) +\n  labs(x = NULL, y = \"Percentage of Variance\", fill = NULL) +\n  theme(legend.position = \"top\")\n\n# Panel C: Hour of day patterns\npanel_c <- hourly_telemetry |>\n  filter(pid %in% unique(dat_desc$pid)) |>\n  mutate(hour = hour(hour_start_local)) |>\n  group_by(pid, hour) |>\n  summarise(total_minutes = sum(minutes, na.rm = TRUE), .groups = \"drop\") |>\n  group_by(hour) |>\n  summarise(\n    mean_minutes = mean(total_minutes, na.rm = TRUE),\n    se = sd(total_minutes, na.rm = TRUE) / sqrt(n()),\n    .groups = \"drop\"\n  ) |>\n  ggplot(aes(x = hour, y = mean_minutes)) +\n  geom_ribbon(\n    aes(ymin = mean_minutes - 1.96 * se, ymax = mean_minutes + 1.96 * se),\n    fill = colors$global_nf,\n    alpha = 0.2\n  ) +\n  geom_line(color = colors$global_nf, linewidth = 1) +\n  geom_point(color = colors$global_nf, size = 2) +\n  labs(x = \"Hour of Day\", y = \"Mean Play\\n(minutes)\") +\n  scale_x_continuous(breaks = seq(0, 23, 3))\n\n# Panel D: Platform usage over study days\npanel_d <- daily_telemetry |>\n  mutate(day_local_date = as.Date(day_local)) |>\n  inner_join(\n    dat_desc |>\n      select(pid, date, wave) |>\n      mutate(\n        date_only = as.Date(date),\n        wave_num = as.numeric(as.character(wave))\n      ) |>\n      filter(wave_num <= 30),\n    by = c(\"pid\", \"day_local_date\" = \"date_only\"),\n    relationship = \"many-to-many\"\n  ) |>\n  filter(minutes > 0) |>\n  mutate(\n    platform = case_when(\n      platform == \"nintendo\" ~ \"Nintendo\",\n      platform == \"xbox\" ~ \"Xbox\",\n      platform == \"steam\" ~ \"Steam\",\n      TRUE ~ platform\n    )\n  ) |>\n  group_by(wave_num, platform) |>\n  summarise(total_minutes = sum(minutes), .groups = \"drop\") |>\n  group_by(wave_num) |>\n  mutate(proportion = total_minutes / sum(total_minutes)) |>\n  ggplot(aes(x = wave_num, y = proportion, fill = platform)) +\n  geom_area(alpha = 0.7, position = \"stack\") +\n  scale_fill_manual(\n    values = c(\n      \"Nintendo\" = colors$nintendo,\n      \"Xbox\" = colors$xbox,\n      \"Steam\" = colors$steam\n    )\n  ) +\n  labs(x = \"Study Day\", y = \"Proportion of Play\", fill = \"Platform\") +\n  scale_x_continuous(breaks = seq(0, 30, 5)) +\n  scale_y_continuous(labels = scales::percent_format()) +\n  theme(legend.position = \"top\")\n\n# Combine panels: top row with 3 panels, bottom row with full-width panel\n((panel_a | panel_b | panel_c) / panel_d) +\n  plot_annotation(tag_levels = \"A\") &\n  theme(\n    plot.background = element_rect(fill = \"white\", color = NA),\n    panel.background = element_rect(fill = \"white\", color = NA)\n  )\n```\n\n::: {.cell-output-display}\n![Descriptive statistics for key variables. (A) Distributions of need satisfaction and frustration variables. (B) Variance decomposition showing proportion of variance at within-person vs between-person levels. (C) Play volume by hour of day (local time). (D) Proportion of play on each platform across study days 1-30.](manuscript_files/figure-html/fig-descriptives-1.png){#fig-descriptives fig-align='center' width=80%}\n:::\n:::\n\n\n:::\n\n### Measures\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-summary=\"Show code (Calculate reliability for all scales)\"}\nomega_global_ns <- number(\n  omega(\n    surveys |> select(bpnsfs_1, bpnsfs_3, bpnsfs_5),\n    plot = FALSE\n  )$omega.tot,\n  .01\n)\nomega_global_nf <- number(\n  omega(\n    surveys |> select(bpnsfs_2, bpnsfs_4, bpnsfs_6),\n    plot = FALSE\n  )$omega.tot,\n  .01\n)\n\nomega_game_ns <- number(\n  omega(\n    surveys |> select(bangs_1, bangs_3, bangs_5),\n    plot = FALSE\n  )$omega.tot,\n  .01\n)\nomega_game_nf <- number(\n  omega(\n    surveys |> select(bangs_2, bangs_4, bangs_6),\n    plot = FALSE\n  )$omega.tot,\n  .01\n)\n\n# proportion of surveys with subsequent play\n\nprop_subsequent_play <- number(\n  nrow(surveys[surveys$telemetry_played_any_24h, ]) / nrow(surveys) * 100,\n  .1\n)\nminutes_subsequent_play <- number(\n  mean(surveys$play_minutes_24h, na.rm = TRUE),\n  1\n)\nsd_minutes_subsequent_play <- number(\n  sd(surveys$play_minutes_24h, na.rm = TRUE),\n  1\n)\n\n# total hours per platform during 30-day study period\n\nplatform_hours <- daily_telemetry |>\n  mutate(day_local_date = as.Date(day_local)) |>\n  inner_join(\n    surveys |>\n      select(pid, date, wave) |>\n      distinct() |>\n      mutate(\n        date_only = as.Date(date),\n        wave_num = as.numeric(as.character(wave))\n      ) |>\n      filter(wave_num <= 30),\n    by = c(\"pid\", \"day_local_date\" = \"date_only\"),\n    relationship = \"many-to-many\"\n  ) |>\n  group_by(platform) |>\n  summarise(total_hours = sum(minutes, na.rm = TRUE) / 60, .groups = \"drop\")\n\nhours_nintendo <- number(\n  platform_hours |> filter(platform == \"Nintendo\") |> pull(total_hours),\n  1,\n  big.mark = \",\"\n)\nhours_xbox <- number(\n  platform_hours |> filter(platform == \"Xbox\") |> pull(total_hours),\n  1,\n  big.mark = \",\"\n)\nhours_steam <- number(\n  platform_hours |> filter(platform == \"Steam\") |> pull(total_hours),\n  1,\n  big.mark = \",\"\n)\n```\n:::\n\n\nThe measures used in this paper are visualized in @fig-descriptives and detailed below. For other measures in the Open Play study not used here, we refer readers to the Open Play codebook [@BallouEtAl2025Open]. \n\n*Need satisfaction in games*. We measured need satisfaction and frustration in games during the most recent gaming session using 3 items from an abbreviated version of the Basic Psychological Need Satisfaction in Gaming Scale [BANGS, @BallouDeterding2024Basic]. The BANGS assesses autonomy, competence, and relatedness need satisfaction with three items for each need; we selected the highest-loading item for each need for our brief daily measure (e.g., relatedness satisfaction: \"I felt I formed relationships with other players and/or characters.\"). Participants rated each item on a Likert scale from 1 (Strongly disagree) to 7 (Strongly agree). We calculated mean scores for need satisfaction by averaging all three items. Reliability of the composite 3-item need satisfaction index was assessed using McDonald’s omega total ($\\omega_t$ = 0.64 for need satisfaction, $\\omega_t$ 0.65 for need frustration). As needs are conceptually distinct, we expect lower reliability for the composite index than for unidimensional scales.\n\n*Need satisfaction and frustration in daily life*. We measured need satisfaction and frustration in daily life (\"global need satisfaction and frustration\") during the previous 24 hours using the brief version of the Basic Psychological Need Satisfaction and Frustration Scale [@ChenEtAl2015Basic; @MartelaRyan2024Assessing]. This scale includes 6 items, with one item for need satisfaction and one item for need frustration for each of the three needs (e.g., \"Today ... I was able to do things that I really want and value in life\"). Participants rated each item on a Likert scale from 1 (Strongly disagree) to 7 (Strongly agree). We calculated mean scores for need satisfaction and need frustration by averaging the relevant items. Reliability of the composite 3-item need satisfaction index was assessed using McDonald’s omega total ($\\omega_t$ = 0.86 for need satisfaction; $\\omega_t$ = 0.77 for need frustration). As needs are conceptually distinct, we expect lower reliability for this composite index than for unidimensional scales.\n\n*Video game playtime*. We measured video game playtime using digital trace data collected from participants' gaming accounts on Xbox, Steam, and Nintendo Switch. During the 30-day study period, we recorded a total of 866 hours of play on Nintendo Switch, 5,920 hours on Xbox, and 22,963 hours on Steam. For each daily survey, we calculated total minutes played in the 24-hour period following survey completion. We also created a binary variable indicating whether any play occurred during this period. On average, 51.6% of surveys were followed by any play in the subsequent 24 hours, with a mean of 111 minutes (SD = 171).\n\n*Displacement*: We measured displacement of core life domains via an open text field asking participants about the hypothetical alternative activity: \"Think back to your most recent gaming session. If you hadn't played a game, what would you most likely have done instead?\" With LLM assistance from Qwen3-4b-instruct [@qwen3technicalreport], we coded participant responses based on whether they mentioned any of the following activities: work/school responsibilities, social engagements, sleep/eating/fitness, or caretaking---so-called \"core life domains\". We refined the LLM prompt through 5 iterations of manual verification of the 100 random coded responses. We created a boolean variable indicating whether any core life domain was hypothetically displaced. Full materials are provided in the supplement, including the exact LLM prompt used for classification, all raw participant responses, coded outputs, manual verification results, and reproducible code.\n\n::: {.place arguments='top, scope: \"parent\", float: true'}\n\n\n::: {#tbl-descriptive-studyA .cell layout-align=\"center\" tbl-cap='Descriptive statistics for primary Study A and Study B variables, decomposed into between- and within-person components.'}\n\n```{.r .cell-code  code-summary=\"Show code (Build multilevel descriptive statistics table)\"}\n# Decompose a variable's variance into between- and within-person components,\n# using the same var()-based approach as fig-descriptives panel B\ndescribe_multilevel <- function(value, pid) {\n  value <- as.numeric(value)\n  var_total <- var(value, na.rm = TRUE)\n  var_between <- var(tapply(value, pid, mean, na.rm = TRUE), na.rm = TRUE)\n  var_within <- var_total - var_between\n\n  tibble(\n    M = mean(value, na.rm = TRUE),\n    median = median(value, na.rm = TRUE),\n    sd_total = sqrt(var_total),\n    sd_between = sqrt(var_between),\n    sd_within = sqrt(var_within),\n    icc1 = var_between / var_total\n  )\n}\n\ndesc_vars_a <- tribble(\n  ~var                       , ~Variable                     , ~is_pct ,\n  \"game_ns\"                  , \"Game need satisfaction\"      , FALSE   ,\n  \"global_ns\"                , \"Global need satisfaction\"    , FALSE   ,\n  \"global_nf\"                , \"Global need frustration\"     , FALSE   ,\n  \"play_minutes_24h\"         , \"Playtime, next 24h (min)\"    , FALSE   ,\n  \"telemetry_played_any_24h\" , \"Any play, next 24h (%)\"      , TRUE    ,\n  \"displaced_core_domain\"    , \"Displaced a core domain (%)\" , TRUE\n) |>\n  mutate(stats = map(var, ~ describe_multilevel(dat_desc[[.x]], dat_desc$pid)))\n\ndesc_vars_b <- tribble(\n  ~var             , ~Variable                , ~is_pct ,\n  \"game_ns\"        , \"Game need satisfaction\" , FALSE   ,\n  \"session_length\" , \"Session length (min)\"   , FALSE   ,\n  \"session_gap\"    , \"Session gap (hrs)\"      , FALSE\n) |>\n  mutate(stats = map(var, ~ describe_multilevel(pws_wide[[.x]], pws_wide$pid)))\n\ndesc_table <- bind_rows(\n  `Study A` = desc_vars_a,\n  `Study B` = desc_vars_b,\n  .id = \"study\"\n) |>\n  unnest(stats) |>\n  mutate(\n    scale = if_else(is_pct, 100, 1),\n    accuracy = if_else(is_pct, 0.1, 0.01),\n    M = number(M * scale, accuracy),\n    Median = number(median * scale, accuracy),\n    `SD (Total)` = number(sd_total * scale, accuracy),\n    `SD (Between)` = number(sd_between * scale, accuracy),\n    `SD (Within)` = number(sd_within * scale, accuracy),\n    `ICC(1)` = number(icc1, 0.01)\n  ) |>\n  select(\n    study,\n    Variable,\n    M,\n    `Median`,\n    `SD (Total)`,\n    `SD (Between)`,\n    `SD (Within)`,\n    `ICC(1)`\n  )\n\ngroup_rows <- list(\n  \"Study A\" = 1,\n  \"Study B\" = nrow(desc_vars_a) + 1\n)\n\ndesc_table |>\n  select(-study) |>\n  tt(\n    notes = \"SD (Total) is pooled across all observations (person-days in Study A, sessions in Study B); SD (Between) is the SD of person-level means; SD (Within) is the residual person-mean-centered SD. ICC(1) = between-person variance / total variance. Game need satisfaction is on a 1-7 scale in both studies. Study A playtime is in minutes; Study A binary variables are shown as percentages. Study B session length is in minutes and session gap in hours.\"\n  ) |>\n  group_tt(i = group_rows) |>\n  style_tt(fontsize = 0.7) |>\n  style_tt(i = 0, bold = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_nsgxshr5abuc5vqs1lr7 = TinyTable.createTableFunctions(\"tinytable_nsgxshr5abuc5vqs1lr7\");\n      // tinytable span after\n      window.addEventListener('load', function () { tableFns_nsgxshr5abuc5vqs1lr7.spanCell(8, 1, 1, 7) })\n      window.addEventListener('load', function () { tableFns_nsgxshr5abuc5vqs1lr7.spanCell(1, 1, 1, 7) })\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '11', j: 1 }, { i: '11', j: 2 }, { i: '11', j: 3 }, { i: '11', j: 4 }, { i: '11', j: 5 }, { i: '11', j: 6 }, { i: '11', j: 7 } ], css_id: 'tinytable_css_ydhj40g8m1n2rfoeo2px',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '7', j: 4 }, { i: '8', j: 4 }, { i: '9', j: 4 }, { i: '10', j: 4 }, { i: '1', j: 5 }, { i: '2', j: 5 }, { i: '3', j: 5 }, { i: '4', j: 5 }, { i: '5', j: 5 }, { i: '6', j: 5 }, { i: '7', j: 5 }, { i: '8', j: 5 }, { i: '9', j: 5 }, { i: '10', j: 5 }, { i: '1', j: 6 }, { i: '2', j: 6 }, { i: '3', j: 6 }, { i: '4', j: 6 }, { i: '5', j: 6 }, { i: '6', j: 6 }, { i: '7', j: 6 }, { i: '8', j: 6 }, { i: '9', j: 6 }, { i: '10', j: 6 }, { i: '1', j: 7 }, { i: '2', j: 7 }, { i: '3', j: 7 }, { i: '4', j: 7 }, { i: '5', j: 7 }, { i: '6', j: 7 }, { i: '7', j: 7 }, { i: '8', j: 7 }, { i: '9', j: 7 }, { i: '10', j: 7 } ], css_id: 'tinytable_css_07ipqjuzu3uecgtnm7fg',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 } ], css_id: 'tinytable_css_g88o5fhqgrh3fnjux1z8',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_nsgxshr5abuc5vqs1lr7.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_nsgxshr5abuc5vqs1lr7 td.tinytable_css_ydhj40g8m1n2rfoeo2px, #tinytable_nsgxshr5abuc5vqs1lr7 th.tinytable_css_ydhj40g8m1n2rfoeo2px {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-size: 0.7em }\n    #tinytable_nsgxshr5abuc5vqs1lr7 td.tinytable_css_07ipqjuzu3uecgtnm7fg, #tinytable_nsgxshr5abuc5vqs1lr7 th.tinytable_css_07ipqjuzu3uecgtnm7fg { font-size: 0.7em }\n    #tinytable_nsgxshr5abuc5vqs1lr7 td.tinytable_css_g88o5fhqgrh3fnjux1z8, #tinytable_nsgxshr5abuc5vqs1lr7 th.tinytable_css_g88o5fhqgrh3fnjux1z8 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-weight: bold; font-size: 0.7em }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_nsgxshr5abuc5vqs1lr7\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Variable</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">M</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Median</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">SD (Total)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">SD (Between)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">SD (Within)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">ICC(1)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='7'>SD (Total) is pooled across all observations (person-days in Study A, sessions in Study B); SD (Between) is the SD of person-level means; SD (Within) is the residual person-mean-centered SD. ICC(1) = between-person variance / total variance. Game need satisfaction is on a 1-7 scale in both studies. Study A playtime is in minutes; Study A binary variables are shown as percentages. Study B session length is in minutes and session gap in hours.</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Study A</td>\n                  <td data-row=\"1\" data-col=\"2\">Study A</td>\n                  <td data-row=\"1\" data-col=\"3\">Study A</td>\n                  <td data-row=\"1\" data-col=\"4\">Study A</td>\n                  <td data-row=\"1\" data-col=\"5\">Study A</td>\n                  <td data-row=\"1\" data-col=\"6\">Study A</td>\n                  <td data-row=\"1\" data-col=\"7\">Study A</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Game need satisfaction</td>\n                  <td data-row=\"2\" data-col=\"2\">4.89</td>\n                  <td data-row=\"2\" data-col=\"3\">5.00</td>\n                  <td data-row=\"2\" data-col=\"4\">1.12</td>\n                  <td data-row=\"2\" data-col=\"5\">0.77</td>\n                  <td data-row=\"2\" data-col=\"6\">0.81</td>\n                  <td data-row=\"2\" data-col=\"7\">0.48</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Global need satisfaction</td>\n                  <td data-row=\"3\" data-col=\"2\">4.80</td>\n                  <td data-row=\"3\" data-col=\"3\">5.00</td>\n                  <td data-row=\"3\" data-col=\"4\">1.29</td>\n                  <td data-row=\"3\" data-col=\"5\">1.00</td>\n                  <td data-row=\"3\" data-col=\"6\">0.82</td>\n                  <td data-row=\"3\" data-col=\"7\">0.60</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">Global need frustration</td>\n                  <td data-row=\"4\" data-col=\"2\">2.62</td>\n                  <td data-row=\"4\" data-col=\"3\">2.67</td>\n                  <td data-row=\"4\" data-col=\"4\">1.28</td>\n                  <td data-row=\"4\" data-col=\"5\">1.00</td>\n                  <td data-row=\"4\" data-col=\"6\">0.80</td>\n                  <td data-row=\"4\" data-col=\"7\">0.61</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Playtime, next 24h (min)</td>\n                  <td data-row=\"5\" data-col=\"2\">121.47</td>\n                  <td data-row=\"5\" data-col=\"3\">35.00</td>\n                  <td data-row=\"5\" data-col=\"4\">174.98</td>\n                  <td data-row=\"5\" data-col=\"5\">124.54</td>\n                  <td data-row=\"5\" data-col=\"6\">122.92</td>\n                  <td data-row=\"5\" data-col=\"7\">0.51</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">Any play, next 24h (%)</td>\n                  <td data-row=\"6\" data-col=\"2\">56.1</td>\n                  <td data-row=\"6\" data-col=\"3\">100.0</td>\n                  <td data-row=\"6\" data-col=\"4\">49.6</td>\n                  <td data-row=\"6\" data-col=\"5\">33.1</td>\n                  <td data-row=\"6\" data-col=\"6\">37.0</td>\n                  <td data-row=\"6\" data-col=\"7\">0.45</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Displaced a core domain (%)</td>\n                  <td data-row=\"7\" data-col=\"2\">39.9</td>\n                  <td data-row=\"7\" data-col=\"3\">0.0</td>\n                  <td data-row=\"7\" data-col=\"4\">49.0</td>\n                  <td data-row=\"7\" data-col=\"5\">30.9</td>\n                  <td data-row=\"7\" data-col=\"6\">38.0</td>\n                  <td data-row=\"7\" data-col=\"7\">0.40</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">Study B</td>\n                  <td data-row=\"8\" data-col=\"2\">Study B</td>\n                  <td data-row=\"8\" data-col=\"3\">Study B</td>\n                  <td data-row=\"8\" data-col=\"4\">Study B</td>\n                  <td data-row=\"8\" data-col=\"5\">Study B</td>\n                  <td data-row=\"8\" data-col=\"6\">Study B</td>\n                  <td data-row=\"8\" data-col=\"7\">Study B</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">Game need satisfaction</td>\n                  <td data-row=\"9\" data-col=\"2\">5.95</td>\n                  <td data-row=\"9\" data-col=\"3\">6.15</td>\n                  <td data-row=\"9\" data-col=\"4\">0.96</td>\n                  <td data-row=\"9\" data-col=\"5\">0.88</td>\n                  <td data-row=\"9\" data-col=\"6\">0.38</td>\n                  <td data-row=\"9\" data-col=\"7\">0.84</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">Session length (min)</td>\n                  <td data-row=\"10\" data-col=\"2\">62.59</td>\n                  <td data-row=\"10\" data-col=\"3\">44.20</td>\n                  <td data-row=\"10\" data-col=\"4\">55.82</td>\n                  <td data-row=\"10\" data-col=\"5\">37.00</td>\n                  <td data-row=\"10\" data-col=\"6\">41.80</td>\n                  <td data-row=\"10\" data-col=\"7\">0.44</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Session gap (hrs)</td>\n                  <td data-row=\"11\" data-col=\"2\">88.58</td>\n                  <td data-row=\"11\" data-col=\"3\">14.18</td>\n                  <td data-row=\"11\" data-col=\"4\">342.35</td>\n                  <td data-row=\"11\" data-col=\"5\">372.69</td>\n                  <td data-row=\"11\" data-col=\"6\">NA</td>\n                  <td data-row=\"11\" data-col=\"7\">1.19</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n:::\n\n### Data Exclusions\n\nConsistent with Stage 1, we applied preregistered exclusions to telemetry records prior to analysis: we excluded telemetry days with >16 hours total logged play across linked platforms, sessions >8 hours, and sessions logged in the future (indicating logging error or system-clock manipulation). We also excluded survey responses failing the preregistered attention check (duplicate need item responses differing by >1 scale point). As part of preregistered data quality processing, we removed background sessions and verified there were no overlapping sessions after preprocessing, before proceeding to the planned analyses. No additional exclusion criteria beyond those preregistered were introduced.\n\n### Imputation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-summary=\"Show code (Quantify missingness for the imputation prose)\"}\n# Reconstruct the analytical-sample wide table and MICE where-matrix (same\n# functions the imputation stage uses) purely to report missingness rates.\nsw_ms <- build_wide_survey(surveys, min_waves = 15)\nmice_setup_ms <- setup_mice_inputs(sw_ms)\nvars_imp_ms <- names(sw_ms)[mice_setup_ms$methods != \"\"]\n\noverall_miss_pct <- scales::number(100 * mean(mice_setup_ms$where), 0.1)\npct_ppl_with_missing <- scales::number(\n  100 * mean(rowSums(is.na(sw_ms[vars_imp_ms])) > 0),\n  0.1\n)\n```\n:::\n\n\nWe used multiple imputation by chained equations (MICE) with predictive mean matching (PMM) to handle missing data. Missing data were imputed for daily need satisfaction/frustration items (BPNSFS, BANGS) and displacement measures (an average of 21.5% missing cells across 97.3% of participants with at least one wave of missing data). Digital trace data were not imputed because tracking was continuous and automatic; missing data represent recorded absence of play. \n\nFollowing the two-stage protocol from @VonHippel2020How based on fraction of missing information, we used 27 imputations. For all variables, imputed distributions closely overlapped with the observed data (see the Supplement). Models were fit separately to each imputed dataset, and estimates were pooled across imputations using Rubin's rules as implemented in the `mice` package [@vanBuurenGroothuis-Oudshoorn2011mice]. For comparison, complete case analyses are reported in the Appendix (Sensitivity Analysis 4); results do not meaningfully differ from the imputed analyses.\n\n### Deviations from Preregistration\n\nWe made several deviations from our preregistration to ensure we could recruit enough high-quality participants to meet our sample size goals. In our view, none are so severe enough to threaten the validity of the study. Deviations are summarized in @tbl-deviations.\n\n::: {.place arguments='top, scope: \"parent\", float: true'}\n\n\n::: {#tbl-deviations .cell layout-align=\"center\" tbl-cap='Summary of deviations from preregistration'}\n\n```{.r .cell-code  code-summary=\"Show code (Create table of preregistration deviations)\"}\ntibble(\n  `Study Aspect` = c(\n    \"Data collection\",\n    \"Data collection\",\n    \"Data collection\",\n    \"Data collection\",\n    \"Data collection\",\n    \"Data collection\",\n    \"Analysis\"\n  ),\n  Preregistered = c(\n    \"All participants sourced from PureProfile\",\n    \"Screening sample would be nationally representative by ethnicity and gender\",\n    \"Sample consists of participants aged 18--30\",\n    \"To qualify, >=75% of a participant's total gaming must take place on platforms included in the study (Xbox, Steam, Nintendo Switch)\",\n    \"Qualification contingent upon valid digital trace data within last 7 days\",\n    \"Daily surveys sent at 7pm local time\",\n    \"Data would be imputed for all participants given a 50% overall response rate\"\n  ),\n  Actual = c(\n    \"Participants sourced from both PureProfile and Prolific\",\n    \"Approximately 50% of screening was done using quotas for national representativeness by ethnicity and gender; all subsequent sampling used convenience sampling with no quotas\",\n    \"Sample consists of participants aged 18-40\",\n    \"To qualify, >=50% of a participant's total gaming must take place on platforms included in the study (Xbox, Steam, Nintendo Switch)\",\n    \"Qualification contingent upon valid digital trace data within last 14 days\",\n    \"Daily surveys sent at 2pm local time\",\n    \"Data imputed for only participants with an individual 50% response rate\"\n  ),\n  `Justification for Deviation` = c(\n    \"Exhausted PureProfile participant pool before reaching required sample size\",\n    \"Exhausted participant pools of smaller demographic categories on both Prolific and PureProfile before reaching required sample size\",\n    \"(1) Unable to recruit enough participants in the US aged 18--30\",\n    \"Low rates of study qualification at 75% threshold, in large part due to substantial uncaptured Playstation play\",\n    \"Feedback from participants indicating that play during a 7-day period was subject to too many fluctuations (e.g., a busy workweek)\",\n    \"Feedback from participants indicating that evening plans often interfered with survey completion and thus adversely affected response rate\",\n    \"Imputing values for participants with 50--97% missing data is poorly justified; results from the preregistered analysis with imputation for all participants are reported in the Appendix (Sensitivity Analysis 5) and do not meaningfully differ from the main analysis\"\n  )\n) |>\n  tt() |>\n  style_tt(fontsize = 0.7) |>\n  style_tt(i = 0, bold = TRUE, align = \"c\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_e65k1t8va09nh8ykrvs4 = TinyTable.createTableFunctions(\"tinytable_e65k1t8va09nh8ykrvs4\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '7', j: 1 }, { i: '7', j: 2 }, { i: '7', j: 3 }, { i: '7', j: 4 } ], css_id: 'tinytable_css_iedp12g3k4i2p5ihfvlo',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 } ], css_id: 'tinytable_css_rphj40d2tlx59f2vltbg',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 } ], css_id: 'tinytable_css_gr381gcdzeymin73mlu9',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_e65k1t8va09nh8ykrvs4.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_e65k1t8va09nh8ykrvs4 td.tinytable_css_iedp12g3k4i2p5ihfvlo, #tinytable_e65k1t8va09nh8ykrvs4 th.tinytable_css_iedp12g3k4i2p5ihfvlo {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-size: 0.7em }\n    #tinytable_e65k1t8va09nh8ykrvs4 td.tinytable_css_rphj40d2tlx59f2vltbg, #tinytable_e65k1t8va09nh8ykrvs4 th.tinytable_css_rphj40d2tlx59f2vltbg { font-size: 0.7em }\n    #tinytable_e65k1t8va09nh8ykrvs4 td.tinytable_css_gr381gcdzeymin73mlu9, #tinytable_e65k1t8va09nh8ykrvs4 th.tinytable_css_gr381gcdzeymin73mlu9 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-weight: bold; text-align: center; font-size: 0.7em }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_e65k1t8va09nh8ykrvs4\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Study Aspect</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Preregistered</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Actual</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Justification for Deviation</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Data collection</td>\n                  <td data-row=\"1\" data-col=\"2\">All participants sourced from PureProfile</td>\n                  <td data-row=\"1\" data-col=\"3\">Participants sourced from both PureProfile and Prolific</td>\n                  <td data-row=\"1\" data-col=\"4\">Exhausted PureProfile participant pool before reaching required sample size</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Data collection</td>\n                  <td data-row=\"2\" data-col=\"2\">Screening sample would be nationally representative by ethnicity and gender</td>\n                  <td data-row=\"2\" data-col=\"3\">Approximately 50% of screening was done using quotas for national representativeness by ethnicity and gender; all subsequent sampling used convenience sampling with no quotas</td>\n                  <td data-row=\"2\" data-col=\"4\">Exhausted participant pools of smaller demographic categories on both Prolific and PureProfile before reaching required sample size</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Data collection</td>\n                  <td data-row=\"3\" data-col=\"2\">Sample consists of participants aged 18--30</td>\n                  <td data-row=\"3\" data-col=\"3\">Sample consists of participants aged 18-40</td>\n                  <td data-row=\"3\" data-col=\"4\">(1) Unable to recruit enough participants in the US aged 18--30</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">Data collection</td>\n                  <td data-row=\"4\" data-col=\"2\">To qualify, >=75% of a participant's total gaming must take place on platforms included in the study (Xbox, Steam, Nintendo Switch)</td>\n                  <td data-row=\"4\" data-col=\"3\">To qualify, >=50% of a participant's total gaming must take place on platforms included in the study (Xbox, Steam, Nintendo Switch)</td>\n                  <td data-row=\"4\" data-col=\"4\">Low rates of study qualification at 75% threshold, in large part due to substantial uncaptured Playstation play</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Data collection</td>\n                  <td data-row=\"5\" data-col=\"2\">Qualification contingent upon valid digital trace data within last 7 days</td>\n                  <td data-row=\"5\" data-col=\"3\">Qualification contingent upon valid digital trace data within last 14 days</td>\n                  <td data-row=\"5\" data-col=\"4\">Feedback from participants indicating that play during a 7-day period was subject to too many fluctuations (e.g., a busy workweek)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">Data collection</td>\n                  <td data-row=\"6\" data-col=\"2\">Daily surveys sent at 7pm local time</td>\n                  <td data-row=\"6\" data-col=\"3\">Daily surveys sent at 2pm local time</td>\n                  <td data-row=\"6\" data-col=\"4\">Feedback from participants indicating that evening plans often interfered with survey completion and thus adversely affected response rate</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Analysis</td>\n                  <td data-row=\"7\" data-col=\"2\">Data would be imputed for all participants given a 50% overall response rate</td>\n                  <td data-row=\"7\" data-col=\"3\">Data imputed for only participants with an individual 50% response rate</td>\n                  <td data-row=\"7\" data-col=\"4\">Imputing values for participants with 50--97% missing data is poorly justified; results from the preregistered analysis with imputation for all participants are reported in the Appendix (Sensitivity Analysis 5) and do not meaningfully differ from the main analysis</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n:::\n\n### Positive Controls\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-summary=\"Show code (Test positive controls)\"}\n# Use first imputation for positive control check\ncor_playtime <- cor.test(\n  dat$self_reported_weekly_play[dat$.imp == 1],\n  dat$play_minutes_24h[dat$.imp == 1],\n  method = \"pearson\"\n)\n\ncor_playtime_inline <- glue(\n  \"r = {number(cor_playtime$estimate, .01)}, 95% CI [{number(cor_playtime$conf.int[1], .01)}, {number(cor_playtime$conf.int[2], .01)}]\"\n)\n\ncor_lifesat <- cor.test(\n  rowMeans(surveys[, c(\"bpnsfs_1\", \"bpnsfs_3\", \"bpnsfs_5\")], na.rm = FALSE),\n  surveys$life_sat,\n  method = \"pearson\"\n)\n\ncor_lifesat_inline <- glue(\n  \"r = {number(cor_lifesat$estimate, .01)}, 95% CI [{number(cor_lifesat$conf.int[1], .01)}, {number(cor_lifesat$conf.int[2], .01)}]\"\n)\n```\n:::\n\n\nAs specified in the preregistration, we assessed three positive controls designed to assess whether our data were capable of addressing our stated hypotheses. All three passed: self-reported playtime correlated positively with logged playtime (r = 0.28, 95% CI [0.26, 0.30]); global need satisfaction correlated positively with life satisfaction (r = 0.74, 95% CI [0.73, 0.75]); and after preprocessing (e.g., to remove background sessions), there were no overlapping sessions. We therefore proceeded with the planned analyses.\n\n### Analysis Approach\n\nWe tested each hypothesis using multilevel within-between regression models estimated with `glmmTMB` [@BrooksEtAl2017glmmTMB]. Focal predictors were within-person mean-centered, with 30-day person means included to separate day-level from 30-day aggregate associations. All models included random intercepts and AR(1) autocorrelation structures; H1 and H3 additionally included random slopes for day-level predictors, while H2 used random intercepts only due to convergence issues with the binary outcome. No demographic covariates were included, as the within-between specification controls for all time-invariant individual differences.\n\nThis approach isolates day-to-day dynamics: day-level coefficients estimate how much a person's outcome deviates from their own 30-day average when their predictor deviates from their own 30-day average. For example, H1's day-level coefficient answers: 'On days when individuals experience better game need satisfaction than their typical level, do they report higher global need satisfaction than their typical level?' The non-focal 30-day aggregate coefficients capture whether people with generally higher predictor levels also have generally higher outcomes across the study period. Random effects account for stable individual differences (e.g., personality, gaming preferences), and the AR(1) term models temporal autocorrelation in daily data. This specification does not adjust for time-varying confounds; estimates should be interpreted as associations rather than causal effects.\n\n## Study A Results: Confirmatory\n\nWe present visualizations for each hypothesis test in turn; all key estimates are summarized @tbl-main-results.\n\n### H1. Greater in-game need satisfaction is associated with greater global need satisfaction\n\n\n\n::: {.place arguments='top, scope: \"parent\", float: true'}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-summary=\"Show code (Plot H1)\"}\nplot_relationship(\n  model = h1mod,\n  x_var = \"game_ns_cw\",\n  x_label = labels[\"game_ns\"],\n  y_label = labels[\"global_ns\"],\n  color = colors$game_ns,\n  n_keepers = 100,\n  within_vars = c(\"game_ns_cw\"),\n  between_vars = c(\"game_ns_cb\")\n)\n```\n\n::: {.cell-output-display}\n![Estimated global need satisfaction as a function of need satisfaction in games (H1). Individual trajectories shown as gray lines, population-level association shown as blue line with 95% confidence ribbon.](manuscript_files/figure-html/fig-h1-predictions-1.png){#fig-h1-predictions fig-align='center' width=80%}\n:::\n:::\n\n\n:::\n\nResults strongly support H1 (@fig-h1-predictions). At the day level, game need satisfaction was positively associated with global need satisfaction (B = 0.21, SE = 0.02, [95% CI: 0.18, 0.24], t = 13.96, p = <.001). On days when participants experienced game need satisfaction 1 scale point (1--7 scale) above their personal 30-day average, they reported global need satisfaction 0.21 units above their personal 30-day average. \n\nAt the 30-day aggregate level, which was not the focus of our hypothesis about day-to-day dynamics, the association (B = 0.79, SE = 0.04, [95% CI: 0.71, 0.88], t = 18.04, p = <.001) was strong, indicating strong between-individual differences. \n\n### H2. Situational need satisfaction is positively associated with the likelihood of playing in the period after survey completion (H2a), while global need frustration is negatively associated (H2b)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-summary=\"Show code (Extract H2 estimates for reporting)\"}\n# Extract estimates for narrative reporting\nh2_summary <- summary(h2_pooled) |> as_tibble()\n\n# H2a: Game need satisfaction\nh2a_ests <- report_wb_estimate(\n  h2_summary,\n  \"game_ns_cw\",\n  \"game_ns_cb\",\n  accuracy = 0.01,\n  stat_label = \"z\"\n)\nh2a_day_est <- h2a_ests$day_level\nh2a_day_coef <- h2a_ests$day_coef\nh2a_agg_est <- h2a_ests$aggregate\nh2a_agg_coef <- h2a_ests$agg_coef\n\n# H2b: Global need frustration\nh2b_ests <- report_wb_estimate(\n  h2_summary,\n  \"global_nf_cw\",\n  \"global_nf_cb\",\n  accuracy = 0.01,\n  stat_label = \"z\"\n)\nh2b_day_est <- h2b_ests$day_level\nh2b_day_coef <- h2b_ests$day_coef\nh2b_agg_est <- h2b_ests$aggregate\nh2b_agg_coef <- h2b_ests$agg_coef\n```\n:::\n\n\n::: {.place arguments='top, scope: \"parent\", float: true'}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-summary=\"Show code (Plot H2)\"}\n# Panel A: Game need satisfaction\np_h2a <- plot_relationship(\n  model = h2mod,\n  x_var = \"game_ns_cw\",\n  x_label = labels[\"game_ns\"],\n  y_label = \"Pr(played in subsequent 24h)\",\n  color = colors$game_ns,\n  n_keepers = 50,\n  within_vars = c(\"game_ns_cw\", \"global_nf_cw\"),\n  between_vars = c(\"game_ns_cb\", \"global_nf_cb\")\n)\n\n# Panel B: Global need frustration\np_h2b <- plot_relationship(\n  model = h2mod,\n  x_var = \"global_nf_cw\",\n  x_label = labels[\"global_nf\"],\n  y_label = \"Pr(played in subsequent 24h)\",\n  color = colors$global_nf,\n  n_keepers = 50,\n  within_vars = c(\"game_ns_cw\", \"global_nf_cw\"),\n  between_vars = c(\"game_ns_cb\", \"global_nf_cb\")\n)\n\n# Combine with patchwork and set y-axis limits to 0-100%\np_h2a +\n  p_h2b +\n  plot_annotation(tag_levels = \"A\") &\n  coord_cartesian(ylim = c(0, 1)) &\n  theme(plot.tag = element_text(face = \"bold\", size = 14))\n```\n\n::: {.cell-output-display}\n![Estimated probability of playing in subsequent 24 hours. (A) As a function of need satisfaction in games (H2a). (B) As a function of global need frustration (H2b). Individual trajectories shown as gray lines, population-level associations shown with 95% confidence ribbons.](manuscript_files/figure-html/fig-h2-predictions-1.png){#fig-h2-predictions fig-align='center' width=80%}\n:::\n:::\n\n\n:::\n\nWe tested H2a and H2b using a single multilevel within-between logistic regression, where in-game need satisfaction and global need frustration (each within- and between-person centered) predicted a binary variable whether any play happened in the 24-hour period after diary survey completion.\n\nResults support neither H2a or H2b: at the day level, experiencing neither 1 point higher game need satisfaction (B = 0.05, SE = 0.04, [95% CI: -0.03, 0.12], z = 1.22, p = 0.223) nor 1 point higher global need frustration (B = -0.08, SE = 0.04, [95% CI: -0.16, 0.01], z = -1.76, p = 0.079) than usual on a 7-point scale showed meaningful associations with the likelihood of subsequent play (see @fig-h2-predictions). \n\nWe conducted a wide range of sensitivity analyses providing convergent conclusions. key estimates for gaming need satisfaction (game NS) and global need frustration (global NF) remain indistinguishable from 0 in models that:\n\n- use subsequent 6 hours (game NS: B = 0.04; global NF: B = -0.01) or 12 hours (game NS: B = 0.04; global NF: B = -0.02) as the outcome, instead of 24 hours (Sensitivity Analysis 1)\n- use alternative random slopes specifications (game NS: B = 0.04; global NF: B = -0.06) (Sensitivity Analysis 2)\n- use a count model of minutes played in the subsequent 24 hours instead of binary play/no-play (game NS: B = 0.04; global NF: B = -0.08) (Sensitivity Analysis 3)\n- use complete case data instead of imputed data (game NS: B = 0.04; global NF: B = -0.08) (Sensitivity Analysis 4)\n- impute data from the full eligible sample instead of the analytic sample (game NS: B = 0.04; global NF: B = -0.08) (Sensitivity Analysis 5)\n- include an interaction between gaming need satisfaction and global need frustration (game NS: B = 0.04; global NF: B = -0.08; game NS * global NF: B = 0.04) (Sensitivity Analysis 6)\n- use a spline term for gaming need satisfaction and global need frustration, instead of a linear term (Sensitivity Analysis 7)\n- enter each individual need (autonomy, competence, relatedness) as predictors instead of composite need satisfaction or frustration (Sensitivity Analysis 8)\n\nThe 30-day aggregate associations (game need satisfaction: B = -0.01, SE = 0.17, [95% CI: -0.34, 0.32], z = -0.05, p = 0.961; global need frustration: B = -0.02, SE = 0.13, [95% CI: -0.27, 0.24], z = -0.13, p = 0.897) similarly indicate no relationship across individuals; these are reported as exploratory and unrelated to the focal hypotheses about short-term behavioral dynamics. \n\nIn short, results consistently fail to detect an association between situational need satisfaction or global need frustration and subsequent play behavior.\n\n### H3. When gaming displaces a core life domain, global need satisfaction will be lower\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-summary=\"Show code (Extract H3 estimates for reporting)\"}\n# Extract estimates for narrative reporting\nh3_summary <- summary(h3_pooled) |> as_tibble()\nh3_ests <- report_wb_estimate(\n  h3_summary,\n  \"displaced_core_domainTRUE\",\n  term_cb = NULL,\n  accuracy = 0.01\n)\n\nh3_est <- h3_ests$day_level\nh3_coef <- h3_ests$day_coef\n```\n:::\n\n\n::: {.place arguments='top, scope: \"parent\", float: true'}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-summary=\"Show code (Plot H3: displaced activity categories vs global NS)\"}\n# Get raw data from first imputation for visualization\nh3_data <- dat |>\n  filter(.imp == 1, !is.na(displaced_core_domain)) |>\n  mutate(\n    displacement_label = if_else(\n      displaced_core_domain,\n      \"Displaced core domain\",\n      \"Displaced non-core domain\"\n    ),\n    x_numeric = if_else(displaced_core_domain, 2, 1)\n  )\n\n# Calculate means for each group (to match what stat_histinterval will show)\nh3_means <- h3_data |>\n  group_by(x_numeric, displacement_label) |>\n  summarise(mean_ns = mean(global_ns, na.rm = TRUE), .groups = \"drop\")\n\nggplot(h3_data, aes(x = x_numeric, y = global_ns)) +\n  # Raincloud plot with asymmetric histograms\n  stat_histinterval(\n    data = h3_data |> filter(!displaced_core_domain),\n    aes(fill = displacement_label),\n    slab_alpha = 0.5,\n    point_interval = mean_qi,\n    breaks = seq(1, 7, by = .4),\n    interval_color = \"black\",\n    point_color = \"black\",\n    point_size = 3,\n    slab_fill = colors$global_ns,\n    side = \"left\"\n  ) +\n  stat_histinterval(\n    data = h3_data |> filter(displaced_core_domain),\n    aes(fill = displacement_label),\n    slab_alpha = 0.5,\n    point_interval = mean_qi,\n    breaks = seq(1, 7, by = .4),\n    interval_color = \"black\",\n    point_color = \"black\",\n    point_size = 3,\n    slab_fill = colors$global_ns,\n    side = \"right\"\n  ) +\n  # Line connecting the mean point estimates\n  geom_line(\n    data = h3_means,\n    aes(x = x_numeric, y = mean_ns),\n    color = \"black\",\n    linewidth = 0.8,\n    linetype = \"solid\"\n  ) +\n  scale_x_continuous(\n    breaks = c(1, 2),\n    labels = c(\"Displaced non-core\\ndomain\", \"Displaced core\\ndomain\")\n  ) +\n  scale_y_continuous(\n    breaks = 1:7,\n    limits = c(1, 7)\n  ) +\n  labs(\n    x = NULL,\n    y = labels[\"global_ns\"]\n  ) +\n  theme(\n    axis.text.x = element_text(size = 11),\n    panel.grid.major.x = element_blank(),\n    legend.position = \"none\"\n  )\n```\n\n::: {.cell-output-display}\n![Global need satisfaction when gaming was reported to displace vs. not displace a core life domain. Plot shows distribution (histogram) and mean with 80% and 95% quantile intervals.](manuscript_files/figure-html/fig-h3-predictions-1.png){#fig-h3-predictions fig-align='center' width=60%}\n:::\n:::\n\n\n:::\n\nParticipants reported what activity their gaming session displaced 13,348 times across the study. In 5,324 cases (39.9%), gaming displaced a core life domain: sleep, eating, or fitness (*n* = 2,031), social engagements (*n* = 300), work or school (*n* = 1,609), or caretaking (*n* = 35). Gaming most commonly displaced non-core activities such as other digital media use (*n* = 4,201) and other leisure activities (*n* = 1,294).\n\nResults provide very weak support for H3 (B = -0.05, SE = 0.02, [95% CI: -0.09, 0.00], t = -2.14, p = 0.032). When gaming displaced a core life domain rather than a non-core activity, participants reported global need satisfaction -0.05 units lower on average. On a 7-point scale, this difference is extremely small, and the distributions of global need satisfaction when gaming displaced core vs. non-core domains are nearly identical (@fig-h3-predictions).\n\nAn exploratory analysis (Appendix Sensitivity Analysis 10) examined whether this relationship differed for specific displaced life domains. Results showed that need satisfaction was lower when gaming displaced work/school responsibilities and sleep/eating/fitness, but---contrary to expectations---tended to be higher when gaming displaced social engagements or caretaking. \n\n\n::: {#tbl-main-results .cell layout-align=\"center\" tbl-cap='Summary of main hypothesis tests (H1-H3)'}\n\n```{.r .cell-code  code-summary=\"Show code (Create combined results table)\"}\n# Combine all three hypothesis results into one table\nh1_combined <- summary(h1_pooled) |>\n  as_tibble() |>\n  filter(term != \"(Intercept)\", !str_detect(term, \"_cb\")) |>\n  select(term, estimate, std.error, statistic, p.value) |>\n  mutate(\n    Hypothesis = glue(\n      \"{labels[str_remove(term, '_cw$')]} → global need satisfaction\"\n    ),\n    test_stat = \"t\"\n  )\n\nh2_combined <- summary(h2_pooled) |>\n  as_tibble() |>\n  filter(term != \"(Intercept)\", !str_detect(term, \"_cb\")) |>\n  select(term, estimate, std.error, statistic, p.value) |>\n  mutate(\n    Hypothesis = glue(\"{labels[str_remove(term, '_cw$')]} → play\"),\n    test_stat = \"z\"\n  )\n\nh3_combined <- summary(h3_pooled) |>\n  as_tibble() |>\n  filter(term != \"(Intercept)\") |>\n  select(term, estimate, std.error, statistic, p.value) |>\n  mutate(\n    Hypothesis = \"Displaced core domain → global need satisfaction\",\n    test_stat = \"t\"\n  )\n\n# Combine and format\nbind_rows(h1_combined, h2_combined, h3_combined) |>\n  mutate(\n    across(c(estimate, std.error, statistic), ~ round(.x, 3)),\n    p.value = case_when(\n      p.value < 0.001 ~ \"<.001\",\n      TRUE ~ as.character(round(p.value, 3))\n    ),\n    # Create combined test statistic column with appropriate label\n    test_result = glue(\"{statistic} ({test_stat})\")\n  ) |>\n  select(\n    Hypothesis,\n    Estimate = estimate,\n    SE = std.error,\n    `Statistic` = test_result,\n    `p` = p.value\n  ) |>\n  tt() |>\n  style_tt(fontsize = 0.7) |>\n  style_tt(i = 0, bold = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_b266usrcl2j65b56l5pa = TinyTable.createTableFunctions(\"tinytable_b266usrcl2j65b56l5pa\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '4', j: 1 }, { i: '4', j: 2 }, { i: '4', j: 3 }, { i: '4', j: 4 }, { i: '4', j: 5 } ], css_id: 'tinytable_css_o9rhghali8rwf6sev37p',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '1', j: 5 }, { i: '2', j: 5 }, { i: '3', j: 5 } ], css_id: 'tinytable_css_1y2sef7ofiwrquhhvy3e',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 } ], css_id: 'tinytable_css_4sygj7d942u39xtxthbu',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_b266usrcl2j65b56l5pa.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_b266usrcl2j65b56l5pa td.tinytable_css_o9rhghali8rwf6sev37p, #tinytable_b266usrcl2j65b56l5pa th.tinytable_css_o9rhghali8rwf6sev37p {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-size: 0.7em }\n    #tinytable_b266usrcl2j65b56l5pa td.tinytable_css_1y2sef7ofiwrquhhvy3e, #tinytable_b266usrcl2j65b56l5pa th.tinytable_css_1y2sef7ofiwrquhhvy3e { font-size: 0.7em }\n    #tinytable_b266usrcl2j65b56l5pa td.tinytable_css_4sygj7d942u39xtxthbu, #tinytable_b266usrcl2j65b56l5pa th.tinytable_css_4sygj7d942u39xtxthbu {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; font-weight: bold; font-size: 0.7em }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_b266usrcl2j65b56l5pa\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Hypothesis</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Estimate</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">SE</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Statistic</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">p</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Game need satisfaction → global need satisfaction</td>\n                  <td data-row=\"1\" data-col=\"2\">0.213</td>\n                  <td data-row=\"1\" data-col=\"3\">0.015</td>\n                  <td data-row=\"1\" data-col=\"4\">13.96 (t)</td>\n                  <td data-row=\"1\" data-col=\"5\"><.001</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Game need satisfaction → play</td>\n                  <td data-row=\"2\" data-col=\"2\">0.047</td>\n                  <td data-row=\"2\" data-col=\"3\">0.038</td>\n                  <td data-row=\"2\" data-col=\"4\">1.217 (z)</td>\n                  <td data-row=\"2\" data-col=\"5\">0.223</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Global need frustration → play</td>\n                  <td data-row=\"3\" data-col=\"2\">-0.077</td>\n                  <td data-row=\"3\" data-col=\"3\">0.044</td>\n                  <td data-row=\"3\" data-col=\"4\">-1.759 (z)</td>\n                  <td data-row=\"3\" data-col=\"5\">0.079</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">Displaced core domain → global need satisfaction</td>\n                  <td data-row=\"4\" data-col=\"2\">-0.048</td>\n                  <td data-row=\"4\" data-col=\"3\">0.022</td>\n                  <td data-row=\"4\" data-col=\"4\">-2.143 (t)</td>\n                  <td data-row=\"4\" data-col=\"5\">0.032</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n# Study B: Exploratory Evidence from PowerWash Simulator\n\n## Study B Method\n\nTo assess whether our findings generalize beyond the Open Play dataset, we conducted a secondary analysis of data from *PowerWash Simulator* (PWS) [@VuorreEtAl2023intensivea]. PWS is a first-person simulation game where players use pressure washers to clean various objects. The PWS dataset complements the Open Play data because it is highly granular: players were prompted during gameplay to rate their experiences of autonomy, competence, focus, wellbeing, immersion, and enjoyment on 0-100 scales, on average once every 10 minutes throughout a play session. We linked these ratings to play behavior extracted from game logs.\n\nThe original study procedures were granted ethical approval by Oxford University’s Central University Research Ethics Committee (SSH_OII_CIA_21_011).\n\n### Participants\n\nThe characteristics of the full sample of 11,080 players in the PWS dataset are described in @VuorreEtAl2023intensivea; here, we briefly describe the subset of data relevant to our questions. All participants in the original study were over 18 years old and provided informed consent; for inclusion in Study B here participants also needed to have answered at least one mood prompt. The median age was 27 (19, 40; 1st and 9th deciles), and the four most frequent gender responses were Male (4,537, 52.2%), Female (2,675, 30.8%), Non-binary (723, 8.3%), and Transgender (326, 3.7%). Participants were resident in 39 countries, with the USA (4,917, 56.5%), UK (840, 9.7%), Canada (448, 5.2%), and Germany (390, 4.5%) being the most represented. Recruitment happened in multiple waves through multiple avenues inside and outside of the game. Study participation was incentivized through cosmetic in-game rewards (e.g., item skins). \n\n### Measures\n\n*Play sessions* were defined as continuous periods of activity separated by gaps in engagement of at least 30 minutes, yielding 101,602 sessions across 8,969 players. Based on the session timestamps, we calculated two behavioral outcomes: session length (minutes) and session gap (hours; defined as the end timestamp of the previous session and the start timestamp of the subsequent one). \n\n*Need satisfaction* was measured via two in-game prompts on a visual analogue scale from 0 to 100: an autonomy item \"Just now, I was doing the things I really wanted to in Powerwash Simulator” and a competence item \"Just now, I felt competent playing PowerWash Simulator\", each with visual analogue scale endpoints \"Not at all\" and \"As much as possible\". We converted each observation to a 1--7 scale to match Study A's BANGS items. For each session, we took the mean of all autonomy and competence ratings to generate a single need satisfaction indicator (analogously to Study A) and decomposed it into within- and between-person components.\n\n### Analysis Approach\n\nAnalogously to Study A, we estimated the relationship between need satisfaction and outcomes (session length, session gap) using linear mixed effects models, with random intercepts and slopes for each participant. Outcomes were log-transformed due to heavily right-skewed distributions. Following our main analysis approach, we decomposed need satisfaction predictors into within- and between-person components and controlled for previous session length and session gap to isolate need satisfaction effects.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-summary=\"Show code (Study B predictions and reporting)\"}\npred_m1 <- predictions(\n  pws_m1,\n  newdata = datagrid(\n    model = pws_m1,\n    game_ns_cw = c(0, 6),\n    game_ns_cb = 0,\n    prev_session_length = mean(pws_wide$prev_session_length, na.rm = TRUE)\n  ),\n  re.form = NA\n) |>\n  as_tibble() |>\n  arrange(game_ns_cw) |>\n  mutate(\n    estimate = exp(estimate),\n    conf.low = exp(conf.low),\n    conf.high = exp(conf.high)\n  )\n\npws_m1_max_eff <- pred_m1 |>\n  summarise(\n    est = diff(estimate),\n    lo = diff(conf.low),\n    hi = diff(conf.high)\n  ) |>\n  transmute(\n    glue(\n      \"{number(est, accuracy = 0.1)} minutes \",\n      \"[95% CI {number(lo, accuracy = 0.1)}, \",\n      \"{number(hi, accuracy = 0.1)}]\"\n    )\n  ) |>\n  pull()\n\npred_m2 <- predictions(\n  pws_m2,\n  newdata = datagrid(\n    model = pws_m2,\n    game_ns_cw = c(0, 6),\n    game_ns_cb = 0,\n    prev_session_gap = mean(pws_wide$prev_session_gap, na.rm = TRUE)\n  ),\n  re.form = NA\n) |>\n  as_tibble() |>\n  arrange(game_ns_cw) |>\n  mutate(\n    estimate = exp(estimate),\n    conf.low = exp(conf.low),\n    conf.high = exp(conf.high)\n  )\n\npws_m2_max_eff <- pred_m2 |>\n  summarise(\n    est = diff(estimate),\n    lo = diff(conf.low),\n    hi = diff(conf.high)\n  ) |>\n  transmute(\n    glue(\n      \"{number(est, accuracy = 0.1)} hours \",\n      \"[95% CI {number(lo, accuracy = 0.1)}, \",\n      \"{number(hi, accuracy = 0.1)}]\"\n    )\n  ) |>\n  pull()\n\npws_m1_est <- report_lmer_term(pws_m1, \"game_ns_cw\", p_method = \"wald_z\")\npws_m2_est <- report_lmer_term(pws_m2, \"game_ns_cw\", p_method = \"wald_z\")\n\ngame_ns_sd <- number(sd(pws_wide$game_ns_cw, na.rm = TRUE), .01)\n```\n:::\n\n\n::: {.place arguments='top, scope: \"parent\", float: true'}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-summary=\"Show code (Visualize PWS relationships)\"}\n# Generate predictions for session length\npred_m1 <- marginaleffects::predictions(\n  pws_m1,\n  newdata = datagrid(\n    game_ns_cw = seq(\n      min(pws_wide$game_ns_cw, na.rm = TRUE),\n      max(pws_wide$game_ns_cw, na.rm = TRUE),\n      length.out = 100\n    ),\n    game_ns_cb = 0,\n    prev_session_length = mean(pws_wide$prev_session_length, na.rm = TRUE)\n  ),\n  re.form = NA\n) |>\n  as_tibble() |>\n  mutate(\n    # Back-transform from log scale to original scale (minutes)\n    estimate = exp(estimate),\n    conf.low = exp(conf.low),\n    conf.high = exp(conf.high)\n  )\n\n# Generate predictions for session gap\npred_m2 <- marginaleffects::predictions(\n  pws_m2,\n  newdata = datagrid(\n    game_ns_cw = seq(\n      min(pws_wide$game_ns_cw, na.rm = TRUE),\n      max(pws_wide$game_ns_cw, na.rm = TRUE),\n      length.out = 100\n    ),\n    game_ns_cb = 0,\n    prev_session_gap = mean(pws_wide$prev_session_gap, na.rm = TRUE)\n  ),\n  re.form = NA\n) |>\n  as_tibble() |>\n  mutate(\n    # Back-transform from log scale to original scale (hours)\n    estimate = exp(estimate),\n    conf.low = exp(conf.low),\n    conf.high = exp(conf.high)\n  )\n\n# Panel A: Session length\np_m1 <- ggplot(pred_m1, aes(x = game_ns_cw, y = estimate)) +\n  geom_ribbon(\n    aes(ymin = conf.low, ymax = conf.high),\n    alpha = 0.2,\n    fill = colors$game_ns\n  ) +\n  geom_line(color = colors$game_ns, linewidth = 1) +\n  scale_y_log10(\n    breaks = scales::breaks_log(n = 6),\n    labels = scales::label_number()\n  ) +\n  labs(\n    x = labels[\"game_ns\"],\n    y = \"Session length (minutes)\"\n  )\n\n# Panel B: Session gap\np_m2 <- ggplot(pred_m2, aes(x = game_ns_cw, y = estimate)) +\n  geom_ribbon(\n    aes(ymin = conf.low, ymax = conf.high),\n    alpha = 0.2,\n    fill = colors$global_ns\n  ) +\n  geom_line(color = colors$global_ns, linewidth = 1) +\n  scale_y_log10(\n    breaks = scales::breaks_log(n = 6),\n    labels = scales::label_number()\n  ) +\n  labs(\n    x = labels[\"game_ns\"],\n    y = \"Time to next session (hours)\"\n  )\n\n# Combine panels\np_m1 +\n  p_m2 +\n  plot_annotation(tag_levels = \"A\") &\n  theme(plot.tag = element_text(face = \"bold\", size = 14))\n```\n\n::: {.cell-output-display}\n![Relationship between session-to-session fluctuations in need satisfaction and play behavior in PowerWash Simulator. (A) Session length. (B) Time to next session. Shaded regions show 95% confidence intervals. The x-axis spans the largest observed positive and negative within-person deviations in need satisfaction.](manuscript_files/figure-html/fig-study2-results-1.png){#fig-study2-results fig-align='center' width=80%}\n:::\n:::\n\n\n:::\n\n## Study B Results: Exploratory\n\nResults are shown in @fig-study2-results. At the session level, game need satisfaction showed a very weak association with session length (B = 0.015, SE = 0.01, 95% CI [-0.005, 0.035], z = 1.458, p = 0.145). Panel A illustrates that when players experienced higher need satisfaction than their personal average, they did not play meaningfully longer: if a player who typically reported need satisfaction of 1 instead reported a 7, their expected change in session length would be only 6.8 minutes [95% CI -1.4, 16.0].\n\nSimilarly, game need satisfaction showed a weak association with time to next session (B = -0.073, SE = 0.033, 95% CI [-0.137, -0.009], z = -2.235, p = 0.025). Panel B shows that if a player who typically reported need satisfaction of 1 instead reported a 7, their next session would begin -4.1 hours [95% CI -6.0, -1.0] sooner than usual. While this association is significant, given that typical session-to-session deviations in need satisfaction are much smaller (within-person SD = 0.43 points), we interpret the practical relevance to behavior as small. It remains an open question how these motivational factors may influence collective human behavior on the games or games platform levels of analysis.\n\nBroadly, results therefore converge with Study A: Despite examining 101,602 sessions from 8,969 players in a different game using different measures, the pattern of weak behavioral associations replicated. Full model outputs are provided in the Supplement.\n\n# Discussion\n\nAcross Study A and Study B, our findings reveal a consistent pattern: basic psychological needs---whether satisfied in games or frustrated in daily life---show weak or null relationships with subsequent gaming behavior. This apparent disconnect between self-reported and behavioral outcomes has important implications. Self-determination theory, particularly as applied to games, has been extensively validated using self-report measures. Players who report higher need satisfaction also report greater enjoyment, stronger intentions to continue playing, and better wellbeing outcomes [@TyackMekler2020Selfdetermination]; @AdinolfTurkay2019differences; @OliverEtAl2016video; @TamboriniEtAl2011Media; @FormosaEtAl2022Need; @TyackEtAl2020Restorative]. Our results do not challenge these relationships. Rather, they suggest that for individual players, the pathway from needs to actual behavior may be substantially weaker or more complex than the pathway from needs to self-reported experiences and intentions.\n\nOur findings are not the first to report weak links between basic needs and gaming engagement as measured by digital trace data. Motivation was only very weakly associated with total engagement in *League of Legends* [@BruhlmannEtAl2020Motivational]. Competence satisfaction did not meaningfully relate to voluntary engagement in a custom RPG [@KaoEtAl2024How], and satisfaction of all three needs was only very weakly related to playtime in Animal Crossing: New Horizons and Plants vs Zombies: Battle for Neighborville over a 2-week timescale (r = .07, likely too small to be practically significant) [@JohannesEtAl2021Video]. We add to these findings with more comprehensive trace data (spanning 5 platforms in Study A and detailed single-game records in Study B) and higher-frequency wellbeing data. Given accumulating weak links between needs and behavior, we suggest several paths forward.\n\n## Implications for the BANG model\n\nOnly one of BANG's predictions was supported (H1/B6: game needs are positively associated with global needs), consistent with prior literature [@AllenAnderson2018satisfaction; @BallouEtAl2024Basic] and the proposed hierarchical structure at the core of SDT [@Vallerand1997Hierarchical]. However, the behavioral predictions fared poorly: neither in-game positive experiences nor deficits in life in general meaningfully related to subsequent play, and self-reported displacement was negligibly related to wellbeing. All in all, BANG hypotheses B5, B8, and B9 were unsupported in our data.\n\nNull results for theoretical predictions can generally be attributed to (1) lack of statistical power, (2) validity issues (e.g., poor design, poor measures), (3) incorrect auxiliary hypotheses, or (4) theory failure [@Meehl1990Why]. We argue that our study is reasonably well-powered [see @BallouEtAl2025Psychological for simulated sensitivity analyses], and with the exception of H3 whose \"hypothetical displacement\" measure has obvious flaws (see Limitations), uses valid measures---in particular, because we observe real-world behavior.\n\nWe endeavored to test one of the most prominent auxiliary hypotheses present, namely the auxiliary of correct timescale, by comparing 6-hour, 12-hour, and 24-hour time periods, and by triangulating using the PowerWash Simulator dataset, wherein need-related experiences are captured within the session itself. However, none were able to find meaningful support for the behavioral predictions. \n\nWe therefore interpret our results as evidence against certain BANG predictions, necessitating model updating. From a metascientific perspective, model updating after falsification is central to iterative model calibration  and theory modulation [@Meehl1990Why], in which constructs are sharpened, measurement improved, and boundary conditions more precisely articulated. Updating BANG requires identifying *when* and *why* need-related processes do and do not relate to behavioral engagement. \n\nA wholesale revision of BANG is beyond the scope of the current paper, but our results suggest follow-up investigation should be limited to targeted probes aimed at determining whether the null results here reflect (i) temporal misalignment ,for example, it may be that need satisfaction updates expectations on a timescale longer than 24 hours, @BallouDeterding2023Just]; (ii) boundary conditions (for example, if need--behavior links emerge only for specific players, games, or contexts with low constraint and weak habitual control); or (iii) competing processes (for example, if habits, reinforcement histories, and situational affordances dominate short-term behavior, leaving needs to shape preferences rather than actions). Critically, if behavioral effects remain absent under conditions designed to maximise their detectability, BANG’s behavioral claims should be revised or removed rather than further insulated.\n\n## Alternative behavioral frameworks\n\nThe modest associations we found between need experiences and subsequent play behavior suggest that basic psychological needs may not be the primary drivers of short-term gaming engagement. In light of this, we suggest player experience research consider other theoretical frameworks that might provide better or complementary explanations for short-term gaming engagement. We are aware of least three such frameworks.  \n\nBehaviorist and reinforcement-learning accounts emphasize the power of recent rewards and environmental cues, rather than subjective motives, in sustaining behavior [@Skinner1965Science; @Niv2009Reinforcement]. Recent work has expanded and adapted these predictions for the digital media domain [@NorwoodEtAl2026Digital; @JamesTunney2017relationship; @JamesTunney2017need]. Under such models, a primary cause of players re-engaging is that the behavior has been reliably reinforced, not because they recently felt more autonomy, competence, or relatedness. \n\nHabit theory similarly predicts minimal coupling between momentary experiences and action. With sufficient repetition in stable contexts, gaming becomes cue-triggered and automatic, guided by procedural memory rather than conscious motivational states [@OuelletteWood1998Habit; @WoodRunger2016Psychology]. If players typically launch games at particular times or in response to specific cues, need fluctuations may exert little incremental influence over behavior.\n\nA third possibility is regulatory cessation. In homeostatic and cybernetic models, behavior is energized by need- or goal-discrepancies and should weaken once these are reduced; highly satisfying engagement may therefore decrease the likelihood of immediate re-engagement [@Hull1943Principles; @Toates1986Motivational; @CarverScheier2001selfregulation]. Self-determination theory explicitly rejects this logic for psychological needs, arguing that need satisfaction does not produce satiation or motivational decline and may instead sustain intrinsic motivation [@SheldonGunz2009psychological]. However, SDT evidence has primarily relied on self-reported motivation rather than observed behavioral continuation, potentially obscuring homeostatic or satiation-like dynamics that operate at the level of action. In games research, where engagement unfolds as repeated consumption, such regulatory processes may better account for short-term disengagement following highly satisfying play episodes.\n\nEach of these perspectives aligns with broader evidence that subjective intentions and experiences often predict real-world actions only weakly because behavior is multiply determined and heavily constrained by situational affordances [@SheeranWebb2016Intention]. For researchers, our findings therefore suggest that comprehensive models of gaming behavior may need to incorporate reinforcement histories, habits, and regulatory processes alongside need-based motivations [@SharpeEtAl2025Quantifying]. For game developers, they suggest that relying on experiential metrics (e.g., 'fun', satisfaction surveys) may provide an incomplete picture of what sustains engagement. For parents and clinicians, they suggest that efforts to promote healthier play patterns may benefit from structural interventions (e.g., increasing friction, modifying environment to reduce contextual cues) rather than focusing on enhancing need fulfilment.\n\n## The value of open behavioral data\n\nThe introduction to this paper outlined three key limitations in gaming research: lack of researcher access to industry data, temporal mismatch between trace data and surveys, and weak theoretical frameworks. Our study addressed all three by negotiating multi-platform access, implementing daily diaries, and testing theory-driven predictions. Yet the clearest contribution may be demonstrating what becomes visible when self-report is paired with comprehensive behavioral records.\n\nSelf-report measures of play behavior commonly correlates with intrinsic motivation, and thereby higher engagement [@NeysEtAl2014exploring; @KosaUysal2024Exploration]. The trace data reveal a different picture. This disconnect is not unique to SDT or gaming; intention-behavior gaps are well-documented across health behaviors, environmental actions, and consumer choices [@SheeranWebb2016Intention]. Whether or not the underlying reasons are shared across these domains and media use, intention-behavior gaps are particularly consequential in a field where theoretical claims increasingly concern behavior, such as how much people play, when they play, what motivates them to start or stop.\n\nThe broader lesson extends beyond SDT. As gaming research matures beyond simple quantity-based approaches [@BallouEtAl2025How], theories must be validated against behavioral outcomes, not just self-reported proxies. Open player behavior data, sourced through a mix of player-led data sharing infrastructure, industry partnerships, and other mechanisms, is essential for this work. \n\nThere are, however, practical barriers to making such behavioral evidence routine. Privacy and re-identification risks are non-trivial for high-resolution digital trace data, particularly when combined with survey responses, and these risks create understandable reluctance among both participants and data holders [@RocherEtAl2019Estimating]. Industry incentives also rarely align with open scientific practices: the most informative behavioral data are often commercially sensitive, operationally costly to extract, and legally complex to share across jurisdictions. Methodologically, the field also lacks shared standards for defining sessions, handling idle time, linking multi-platform identities, and documenting preprocessing decisions—each of which can meaningfully affect substantive conclusions.\n\nWe therefore advocate for multi-platform solutions, mixing both open source and, where possible with high transparency standards, industry collaborations. Multi-platform coverage matters substantively because platform ecosystems structure when and how people play. Different platforms afford different play contexts (e.g., portable vs. fixed-location play, solitary vs. social defaults, friction to launch, and typical session cadence), and these affordances can shift the distribution of sessions across the day and week. When studies observe only a single platform, they risk misclassifying a person’s true “non-play” periods (e.g., apparent disengagement on one platform may simply reflect switching to another), attenuating within-person associations and obscuring displacement dynamics. Single-platform datasets also risk overgeneralizing from idiosyncratic platform cultures and technical constraints (such as background processes, suspend/resume behavior, or account sharing) that can inflate or distort behavioral measures.\n\n## Limitations and Future Directions\n\nSeveral limitations qualify the interpretation of the present findings. First, although our analyses focus on within-person associations, these estimates should not be interpreted as causal effects [@RohrerMurayama2021These]. Even with high-frequency longitudinal measurement, within-person variation does not isolate exogenous change: need satisfaction may covary with unmeasured situational factors (e.g., time availability, fatigue, social context) that independently shape gaming behavior. Our results therefore speak to the strength of empirical coupling between needs and behavior, not to causal necessity or sufficiency.\n\nSecond, our test of displacement (H3) relies on a hypothetical counterfactual measure: what participants report they would have done had they not played. This approach is coarse and vulnerable to recall bias, rationalisation, and ambiguity in how respondents interpret \"most likely\" alternatives. While the measure provides a useful first pass at identifying potentially displaced life domains, it is ill-suited for detecting subtle or cumulative displacement processes and likely attenuates any true effects. More rigorous tests of displacement will require objective time-use data or designs that directly observe trade-offs between activities.\n\nThird, the behavioral outcomes examined here reflect short-term engagement patterns, such as session length and return latency. Null or weak associations at this timescale do not rule out need-related effects on longer-term outcomes, such as game choice, persistence over months, or disengagement trajectories. Our conclusions are therefore limited to short-term behavioral dynamics and should not be generalized to all forms of gaming involvement.\n\nFourth, while the Study A data represent a substantial advancement in capturing comprehensive multi-platform data, they are nonetheless incomplete: players in our sample may have played games on Playstation, played third-party games on Nintendo, or played on mobile (which, while captured, was not captured in sufficient temporal resolution to inform the hypotheses here). Methods for reliably capturing data from each gaming platform require further development.\n\nFinally, our sample, although purposively sampled for racial and gender diversity, should be understood as consisting of engaged 18--40 year old players willing to share detailed behavioral data and complete intensive surveys, rather than as representative of all players. This selectivity limits generalizability in two ways. First, casual players, younger adolescents, and individuals with minimal or highly irregular play patterns are underrepresented. Second, highly engaged players' behavior may differ systematically from those among less engaged populations (e.g,more routinized or more highly habit-driven). The weak need–behavior associations observed here may not generalize to all player groups, nor do they preclude stronger effects in populations with greater variability in motivation or fewer structural constraints.\n\nTogether, these limitations suggest that the present findings should be interpreted as strong evidence against large, general, short-term behavioral effects of need satisfaction among engaged adult players, rather than as definitive evidence against any role for psychological needs in shaping gaming behavior more broadly.\n\n## Data Availability\n\nAll data, materials, and code related to the dataset and this manuscript are available under {{< meta data-license >}} at {{< meta data-url >}}.\n\n## Funding\n\nThis research was supported by the UK Economic and Social Research Council (ES/W012626/1 and ES/Y010736/1). AP was supported by the Huo Family Foundation. \n\n## Conflicts of Interest\n\nThe authors declare no competing financial, intellectual, or institutional interests relevant to this research. The disclosures below are provided in the interest of full transparency.\n\nAll members of the research team have worked on scientific projects funded by government and charitable grants that used data from tech companies provided under a data-sharing agreement. No authors have received funding or compensation from the tech companies or other industries connected to the work presented here. \n\nMV has provided in-kind consultations and served as a nonpaid panel member for Meta and K-Games. AKP has served in advisory or expert roles for the Sync Digital Wellbeing Program (2022–2024), the Google Expert Advisory on Youth and Technology (2025), the OpenAI Expert Council on Well-Being and AI (2025), and UK Department for Science, Innovation and Technology–funded research on children’s smartphone and social media use (University of Cambridge, 2025). He is a member of the UK Department for Culture, Media & Sport College of Experts. Any industry fees are directly donated to charity, and his research is conducted in accordance with University of Oxford academic integrity policies.\n\nData-sharing partners had no role in the design, analysis, or publication of results. \n\n\n# References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "manuscript_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}